"""
Strategy Engine - Core Strategy Execution System
Advanced strategy execution framework with lifecycle management and monitoring
"""

import logging
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Union, Any, Tuple, Set, Callable
from dataclasses import dataclass, field
from enum import Enum
from abc import ABC, abstractmethod
import asyncio
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
import time
import warnings
from collections import defaultdict, deque
import json

warnings.filterwarnings('ignore')
logger = logging.getLogger(__name__)


class StrategyState(Enum):
    """Strategy execution states"""
    INACTIVE = "inactive"
    INITIALIZING = "initializing"
    ACTIVE = "active"
    PAUSED = "paused"
    STOPPING = "stopping"
    STOPPED = "stopped"
    ERROR = "error"
    WARMING_UP = "warming_up"


class StrategyType(Enum):
    """Strategy types"""
    MEAN_REVERSION = "mean_reversion"
    MOMENTUM = "momentum"
    PAIRS_TRADING = "pairs_trading"
    ARBITRAGE = "arbitrage"
    MARKET_MAKING = "market_making"
    TREND_FOLLOWING = "trend_following"
    STATISTICAL_ARBITRAGE = "statistical_arbitrage"
    MULTI_FACTOR = "multi_factor"
    MACHINE_LEARNING = "machine_learning"
    VOLATILITY = "volatility"
    CUSTOM = "custom"


class SignalType(Enum):
    """Trading signal types"""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    CLOSE_LONG = "close_long"
    CLOSE_SHORT = "close_short"
    REDUCE_LONG = "reduce_long"
    REDUCE_SHORT = "reduce_short"
    INCREASE_LONG = "increase_long"
    INCREASE_SHORT = "increase_short"


class RiskLevel(Enum):
    """Risk levels for strategy execution"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class StrategySignal:
    """Trading signal generated by strategy"""
    
    # Signal identification
    signal_id: str = ""
    strategy_id: str = ""
    timestamp: datetime = field(default_factory=datetime.now)
    
    # Signal details
    symbol: str = ""
    signal_type: SignalType = SignalType.HOLD
    confidence: float = 0.0  # 0.0 to 1.0
    strength: float = 0.0    # Signal strength
    
    # Position sizing
    target_quantity: float = 0.0
    target_weight: Optional[float] = None
    position_side: str = "long"  # long, short
    
    # Price information
    signal_price: Optional[float] = None
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    
    # Risk management
    max_position_size: Optional[float] = None
    risk_limit: Optional[float] = None
    holding_period: Optional[int] = None  # Expected holding period in minutes
    
    # Signal metadata
    signal_source: str = ""  # Which component generated this signal
    signal_reason: str = ""  # Why this signal was generated
    additional_data: Dict[str, Any] = field(default_factory=dict)
    
    # Execution tracking
    is_executed: bool = False
    execution_time: Optional[datetime] = None
    execution_price: Optional[float] = None
    execution_quantity: Optional[float] = None


@dataclass
class StrategyPosition:
    """Strategy position tracking"""
    
    # Position identification
    position_id: str = ""
    strategy_id: str = ""
    symbol: str = ""
    
    # Position details
    quantity: float = 0.0
    side: str = "long"  # long, short
    entry_price: float = 0.0
    current_price: float = 0.0
    market_value: float = 0.0
    
    # Risk management
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    max_loss: Optional[float] = None
    
    # Performance tracking
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    total_pnl: float = 0.0
    
    # Timing
    entry_time: datetime = field(default_factory=datetime.now)
    holding_period: int = 0  # Minutes
    last_update: datetime = field(default_factory=datetime.now)
    
    # Position metadata
    position_source: str = ""
    additional_data: Dict[str, Any] = field(default_factory=dict)


@dataclass
class StrategyMetrics:
    """Strategy performance metrics"""
    
    # Basic metrics
    total_signals: int = 0
    executed_signals: int = 0
    successful_signals: int = 0
    signal_success_rate: float = 0.0
    
    # Performance metrics
    total_return: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    max_drawdown: float = 0.0
    
    # Risk metrics
    sharpe_ratio: float = 0.0
    volatility: float = 0.0
    var_95: float = 0.0
    
    # Position metrics
    active_positions: int = 0
    total_positions: int = 0
    avg_holding_period: float = 0.0
    
    # Execution metrics
    avg_execution_time: float = 0.0
    slippage: float = 0.0
    transaction_costs: float = 0.0
    
    # Timing metrics
    last_signal_time: Optional[datetime] = None
    last_execution_time: Optional[datetime] = None
    strategy_uptime: float = 0.0  # Percentage
    
    # Error metrics
    error_count: int = 0
    warning_count: int = 0
    last_error_time: Optional[datetime] = None


@dataclass
class StrategyConfig:
    """Strategy configuration"""
    
    # Basic settings
    strategy_id: str = ""
    strategy_name: str = ""
    strategy_type: StrategyType = StrategyType.CUSTOM
    description: str = ""
    
    # Execution settings
    enable_live_trading: bool = False
    paper_trading_mode: bool = True
    max_positions: int = 10
    max_position_size: float = 0.1  # 10% of portfolio
    
    # Risk management
    max_daily_loss: float = 0.05    # 5% daily loss limit
    max_total_exposure: float = 1.0  # 100% exposure limit
    position_sizing_method: str = "fixed_percentage"
    risk_per_trade: float = 0.02    # 2% risk per trade
    
    # Signal settings
    min_signal_confidence: float = 0.6
    min_signal_strength: float = 0.5
    signal_timeout: int = 300  # 5 minutes
    
    # Data settings
    required_symbols: List[str] = field(default_factory=list)
    required_data_feeds: List[str] = field(default_factory=list)
    warmup_period: int = 100  # Number of data points for warmup
    
    # Performance settings
    benchmark_symbol: str = "SPY"
    performance_update_frequency: int = 60  # seconds
    enable_real_time_monitoring: bool = True
    
    # Strategy parameters (strategy-specific)
    strategy_parameters: Dict[str, Any] = field(default_factory=dict)
    
    # Execution settings
    execution_timeout: float = 30.0
    max_slippage: float = 0.001  # 0.1% max slippage
    enable_stop_loss: bool = True
    enable_take_profit: bool = True


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies
    
    Defines the interface that all strategies must implement
    """
    
    def __init__(self, config: StrategyConfig):
        self.config = config
        self.strategy_id = config.strategy_id
        self.state = StrategyState.INACTIVE
        
        # Strategy data
        self._positions: Dict[str, StrategyPosition] = {}
        self._signals: List[StrategySignal] = []
        self._metrics = StrategyMetrics()
        
        # Data storage
        self._market_data: Dict[str, pd.DataFrame] = {}
        self._indicators: Dict[str, pd.Series] = {}
        
        # Timing
        self._start_time: Optional[datetime] = None
        self._last_update: Optional[datetime] = None
        
        logger.info(f"Base strategy initialized: {self.strategy_id}")
    
    @abstractmethod
    def initialize(self) -> bool:
        """Initialize strategy - must be implemented by subclasses"""
        pass
    
    @abstractmethod
    def generate_signals(self, market_data: Dict[str, pd.DataFrame]) -> List[StrategySignal]:
        """Generate trading signals - must be implemented by subclasses"""
        pass
    
    @abstractmethod
    def update_positions(self, market_data: Dict[str, pd.DataFrame]) -> None:
        """Update position tracking - must be implemented by subclasses"""
        pass
    
    def start(self) -> bool:
        """Start strategy execution"""
        try:
            if self.state != StrategyState.INACTIVE:
                logger.warning(f"Strategy {self.strategy_id} not in inactive state")
                return False
            
            self.state = StrategyState.INITIALIZING
            
            if not self.initialize():
                self.state = StrategyState.ERROR
                return False
            
            self.state = StrategyState.ACTIVE
            self._start_time = datetime.now()
            
            logger.info(f"Strategy {self.strategy_id} started successfully")
            return True
            
        except Exception as e:
            logger.error(f"Error starting strategy {self.strategy_id}: {e}")
            self.state = StrategyState.ERROR
            return False
    
    def stop(self) -> bool:
        """Stop strategy execution"""
        try:
            if self.state not in [StrategyState.ACTIVE, StrategyState.PAUSED]:
                logger.warning(f"Strategy {self.strategy_id} not in active/paused state")
                return False
            
            self.state = StrategyState.STOPPING
            
            # Close all positions if configured
            if hasattr(self.config, 'close_positions_on_stop') and self.config.close_positions_on_stop:
                self._close_all_positions()
            
            self.state = StrategyState.STOPPED
            
            logger.info(f"Strategy {self.strategy_id} stopped successfully")
            return True
            
        except Exception as e:
            logger.error(f"Error stopping strategy {self.strategy_id}: {e}")
            self.state = StrategyState.ERROR
            return False
    
    def pause(self) -> bool:
        """Pause strategy execution"""
        try:
            if self.state != StrategyState.ACTIVE:
                logger.warning(f"Strategy {self.strategy_id} not in active state")
                return False
            
            self.state = StrategyState.PAUSED
            logger.info(f"Strategy {self.strategy_id} paused")
            return True
            
        except Exception as e:
            logger.error(f"Error pausing strategy {self.strategy_id}: {e}")
            return False
    
    def resume(self) -> bool:
        """Resume strategy execution"""
        try:
            if self.state != StrategyState.PAUSED:
                logger.warning(f"Strategy {self.strategy_id} not in paused state")
                return False
            
            self.state = StrategyState.ACTIVE
            logger.info(f"Strategy {self.strategy_id} resumed")
            return True
            
        except Exception as e:
            logger.error(f"Error resuming strategy {self.strategy_id}: {e}")
            return False
    
    def update(self, market_data: Dict[str, pd.DataFrame]) -> List[StrategySignal]:
        """Update strategy with new market data"""
        try:
            if self.state != StrategyState.ACTIVE:
                return []
            
            self._last_update = datetime.now()
            self._market_data.update(market_data)
            
            # Update positions
            self.update_positions(market_data)
            
            # Generate new signals
            new_signals = self.generate_signals(market_data)
            
            # Validate and filter signals
            valid_signals = self._validate_signals(new_signals)
            
            # Update signals list
            self._signals.extend(valid_signals)
            
            # Update metrics
            self._update_metrics()
            
            return valid_signals
            
        except Exception as e:
            logger.error(f"Error updating strategy {self.strategy_id}: {e}")
            self._metrics.error_count += 1
            self._metrics.last_error_time = datetime.now()
            return []
    
    def _validate_signals(self, signals: List[StrategySignal]) -> List[StrategySignal]:
        """Validate generated signals"""
        valid_signals = []
        
        for signal in signals:
            # Check signal confidence
            if signal.confidence < self.config.min_signal_confidence:
                continue
            
            # Check signal strength
            if signal.strength < self.config.min_signal_strength:
                continue
            
            # Check position limits
            if len(self._positions) >= self.config.max_positions:
                continue
            
            # Check if signal is for existing position
            if signal.symbol in self._positions:
                # Handle position modification signals
                pass
            
            valid_signals.append(signal)
        
        return valid_signals
    
    def _close_all_positions(self) -> None:
        """Close all strategy positions"""
        try:
            for position in self._positions.values():
                # Generate close signal
                close_signal = StrategySignal(
                    signal_id=f"close_{position.position_id}",
                    strategy_id=self.strategy_id,
                    symbol=position.symbol,
                    signal_type=SignalType.CLOSE_LONG if position.side == "long" else SignalType.CLOSE_SHORT,
                    confidence=1.0,
                    strength=1.0,
                    target_quantity=abs(position.quantity),
                    signal_reason="Strategy stop - close all positions"
                )
                
                self._signals.append(close_signal)
            
            logger.info(f"Generated close signals for {len(self._positions)} positions")
            
        except Exception as e:
            logger.error(f"Error closing all positions: {e}")
    
    def _update_metrics(self) -> None:
        """Update strategy metrics"""
        try:
            # Basic metrics
            self._metrics.total_signals = len(self._signals)
            self._metrics.executed_signals = sum(1 for s in self._signals if s.is_executed)
            
            if self._metrics.total_signals > 0:
                self._metrics.signal_success_rate = self._metrics.executed_signals / self._metrics.total_signals
            
            # Position metrics
            self._metrics.active_positions = len(self._positions)
            
            # Performance metrics
            total_unrealized = sum(pos.unrealized_pnl for pos in self._positions.values())
            total_realized = sum(pos.realized_pnl for pos in self._positions.values())
            
            self._metrics.unrealized_pnl = total_unrealized
            self._metrics.realized_pnl = total_realized
            self._metrics.total_return = total_unrealized + total_realized
            
            # Timing metrics
            if self._signals:
                self._metrics.last_signal_time = max(s.timestamp for s in self._signals)
            
            if self._start_time:
                uptime = (datetime.now() - self._start_time).total_seconds()
                if self.state == StrategyState.ACTIVE:
                    self._metrics.strategy_uptime = 100.0
                else:
                    # Calculate actual uptime percentage
                    pass
            
        except Exception as e:
            logger.error(f"Error updating metrics: {e}")
    
    def get_positions(self) -> Dict[str, StrategyPosition]:
        """Get current strategy positions"""
        return self._positions.copy()
    
    def get_signals(self, limit: Optional[int] = None) -> List[StrategySignal]:
        """Get strategy signals"""
        if limit:
            return self._signals[-limit:]
        return self._signals.copy()
    
    def get_metrics(self) -> StrategyMetrics:
        """Get strategy metrics"""
        return self._metrics
    
    def get_state(self) -> StrategyState:
        """Get strategy state"""
        return self.state


class StrategyExecutionEngine:
    """
    Strategy Execution Engine
    
    Manages the execution lifecycle of trading strategies including
    initialization, data management, signal processing, and monitoring.
    """
    
    def __init__(self, max_concurrent_strategies: int = 10):
        """Initialize strategy execution engine"""
        
        self.max_concurrent_strategies = max_concurrent_strategies
        
        # Strategy management
        self._strategies: Dict[str, BaseStrategy] = {}
        self._strategy_configs: Dict[str, StrategyConfig] = {}
        
        # Execution control
        self._execution_active = False
        self._execution_thread: Optional[threading.Thread] = None
        self._stop_event = threading.Event()
        
        # Data management
        self._market_data_cache: Dict[str, pd.DataFrame] = {}
        self._last_data_update: Optional[datetime] = None
        
        # Signal management
        self._signal_queue: deque = deque()
        self._signal_history: List[StrategySignal] = []
        
        # Performance tracking
        self._engine_metrics = {
            'strategies_registered': 0,
            'strategies_active': 0,
            'total_signals_generated': 0,
            'total_signals_executed': 0,
            'execution_cycles': 0,
            'avg_cycle_time': 0.0,
            'errors': 0,
            'warnings': 0,
            'uptime_start': None,
            'last_update': None
        }
        
        # Thread safety
        self._lock = threading.RLock()
        
        # Signal processors
        self._signal_processors: List[Callable[[StrategySignal], bool]] = []
        
        logger.info("Strategy execution engine initialized")
    
    def register_strategy(self, strategy: BaseStrategy) -> bool:
        """Register a strategy with the engine"""
        
        try:
            with self._lock:
                if strategy.strategy_id in self._strategies:
                    logger.warning(f"Strategy {strategy.strategy_id} already registered")
                    return False
                
                if len(self._strategies) >= self.max_concurrent_strategies:
                    logger.error(f"Maximum concurrent strategies ({self.max_concurrent_strategies}) reached")
                    return False
                
                self._strategies[strategy.strategy_id] = strategy
                self._strategy_configs[strategy.strategy_id] = strategy.config
                
                self._engine_metrics['strategies_registered'] += 1
                
                logger.info(f"Strategy {strategy.strategy_id} registered successfully")
                return True
                
        except Exception as e:
            logger.error(f"Error registering strategy {strategy.strategy_id}: {e}")
            return False
    
    def unregister_strategy(self, strategy_id: str) -> bool:
        """Unregister a strategy from the engine"""
        
        try:
            with self._lock:
                if strategy_id not in self._strategies:
                    logger.warning(f"Strategy {strategy_id} not found")
                    return False
                
                strategy = self._strategies[strategy_id]
                
                # Stop strategy if active
                if strategy.get_state() == StrategyState.ACTIVE:
                    strategy.stop()
                
                # Remove from engine
                del self._strategies[strategy_id]
                del self._strategy_configs[strategy_id]
                
                logger.info(f"Strategy {strategy_id} unregistered successfully")
                return True
                
        except Exception as e:
            logger.error(f"Error unregistering strategy {strategy_id}: {e}")
            return False
    
    def start_strategy(self, strategy_id: str) -> bool:
        """Start a specific strategy"""
        
        try:
            with self._lock:
                if strategy_id not in self._strategies:
                    logger.error(f"Strategy {strategy_id} not found")
                    return False
                
                strategy = self._strategies[strategy_id]
                result = strategy.start()
                
                if result:
                    self._engine_metrics['strategies_active'] += 1
                
                return result
                
        except Exception as e:
            logger.error(f"Error starting strategy {strategy_id}: {e}")
            return False
    
    def stop_strategy(self, strategy_id: str) -> bool:
        """Stop a specific strategy"""
        
        try:
            with self._lock:
                if strategy_id not in self._strategies:
                    logger.error(f"Strategy {strategy_id} not found")
                    return False
                
                strategy = self._strategies[strategy_id]
                result = strategy.stop()
                
                if result and self._engine_metrics['strategies_active'] > 0:
                    self._engine_metrics['strategies_active'] -= 1
                
                return result
                
        except Exception as e:
            logger.error(f"Error stopping strategy {strategy_id}: {e}")
            return False
    
    def start_all_strategies(self) -> Dict[str, bool]:
        """Start all registered strategies"""
        
        results = {}
        
        with self._lock:
            for strategy_id in self._strategies.keys():
                results[strategy_id] = self.start_strategy(strategy_id)
        
        successful = sum(1 for result in results.values() if result)
        logger.info(f"Started {successful}/{len(results)} strategies")
        
        return results
    
    def stop_all_strategies(self) -> Dict[str, bool]:
        """Stop all active strategies"""
        
        results = {}
        
        with self._lock:
            for strategy_id, strategy in self._strategies.items():
                if strategy.get_state() == StrategyState.ACTIVE:
                    results[strategy_id] = self.stop_strategy(strategy_id)
        
        logger.info(f"Stopped {len(results)} strategies")
        
        return results
    
    def start_execution(self) -> bool:
        """Start the execution engine"""
        
        try:
            if self._execution_active:
                logger.warning("Execution engine already running")
                return False
            
            self._execution_active = True
            self._stop_event.clear()
            
            # Start execution thread
            self._execution_thread = threading.Thread(
                target=self._execution_loop,
                daemon=True
            )
            self._execution_thread.start()
            
            self._engine_metrics['uptime_start'] = datetime.now()
            
            logger.info("Strategy execution engine started")
            return True
            
        except Exception as e:
            logger.error(f"Error starting execution engine: {e}")
            self._execution_active = False
            return False
    
    def stop_execution(self) -> bool:
        """Stop the execution engine"""
        
        try:
            if not self._execution_active:
                logger.warning("Execution engine not running")
                return False
            
            # Stop all strategies first
            self.stop_all_strategies()
            
            # Signal stop and wait for thread
            self._stop_event.set()
            self._execution_active = False
            
            if self._execution_thread and self._execution_thread.is_alive():
                self._execution_thread.join(timeout=5.0)
            
            logger.info("Strategy execution engine stopped")
            return True
            
        except Exception as e:
            logger.error(f"Error stopping execution engine: {e}")
            return False
    
    def update_market_data(self, symbol: str, data: pd.DataFrame) -> None:
        """Update market data for strategies"""
        
        try:
            with self._lock:
                self._market_data_cache[symbol] = data
                self._last_data_update = datetime.now()
                
        except Exception as e:
            logger.error(f"Error updating market data for {symbol}: {e}")
    
    def add_signal_processor(self, processor: Callable[[StrategySignal], bool]) -> None:
        """Add a signal processor function"""
        
        with self._lock:
            self._signal_processors.append(processor)
        
        logger.info("Signal processor added")
    
    def _execution_loop(self) -> None:
        """Main execution loop"""
        
        logger.info("Strategy execution loop started")
        
        while not self._stop_event.is_set() and self._execution_active:
            try:
                cycle_start = time.time()
                
                # Update all active strategies
                self._update_strategies()
                
                # Process signals
                self._process_signals()
                
                # Update engine metrics
                self._update_engine_metrics()
                
                # Calculate cycle time
                cycle_time = time.time() - cycle_start
                
                # Update average cycle time
                self._engine_metrics['execution_cycles'] += 1
                total_time = (self._engine_metrics['avg_cycle_time'] * 
                            (self._engine_metrics['execution_cycles'] - 1) + cycle_time)
                self._engine_metrics['avg_cycle_time'] = total_time / self._engine_metrics['execution_cycles']
                
                # Sleep to maintain reasonable cycle frequency
                time.sleep(max(0.1, 1.0 - cycle_time))  # Target 1 second cycles
                
            except Exception as e:
                logger.error(f"Error in execution loop: {e}")
                self._engine_metrics['errors'] += 1
                time.sleep(1.0)  # Brief pause on error
        
        logger.info("Strategy execution loop stopped")
    
    def _update_strategies(self) -> None:
        """Update all active strategies with latest market data"""
        
        try:
            with self._lock:
                active_strategies = [
                    strategy for strategy in self._strategies.values()
                    if strategy.get_state() == StrategyState.ACTIVE
                ]
                
                if not active_strategies:
                    return
                
                # Update each strategy
                for strategy in active_strategies:
                    try:
                        # Filter market data for strategy's required symbols
                        strategy_data = {}
                        required_symbols = strategy.config.required_symbols
                        
                        if required_symbols:
                            for symbol in required_symbols:
                                if symbol in self._market_data_cache:
                                    strategy_data[symbol] = self._market_data_cache[symbol]
                        else:
                            # Use all available data if no specific symbols required
                            strategy_data = self._market_data_cache.copy()
                        
                        # Update strategy
                        new_signals = strategy.update(strategy_data)
                        
                        # Add signals to queue
                        for signal in new_signals:
                            self._signal_queue.append(signal)
                            self._signal_history.append(signal)
                        
                        self._engine_metrics['total_signals_generated'] += len(new_signals)
                        
                    except Exception as e:
                        logger.error(f"Error updating strategy {strategy.strategy_id}: {e}")
                        self._engine_metrics['errors'] += 1
                
        except Exception as e:
            logger.error(f"Error in strategy update: {e}")
            self._engine_metrics['errors'] += 1
    
    def _process_signals(self) -> None:
        """Process signals in the signal queue"""
        
        try:
            while self._signal_queue:
                signal = self._signal_queue.popleft()
                
                # Process signal through registered processors
                processed = True
                for processor in self._signal_processors:
                    try:
                        if not processor(signal):
                            processed = False
                            break
                    except Exception as e:
                        logger.error(f"Error in signal processor: {e}")
                        processed = False
                        break
                
                if processed:
                    signal.is_executed = True
                    signal.execution_time = datetime.now()
                    self._engine_metrics['total_signals_executed'] += 1
                
        except Exception as e:
            logger.error(f"Error processing signals: {e}")
            self._engine_metrics['errors'] += 1
    
    def _update_engine_metrics(self) -> None:
        """Update engine metrics"""
        
        try:
            self._engine_metrics['last_update'] = datetime.now()
            
            # Count active strategies
            active_count = sum(
                1 for strategy in self._strategies.values()
                if strategy.get_state() == StrategyState.ACTIVE
            )
            self._engine_metrics['strategies_active'] = active_count
            
        except Exception as e:
            logger.error(f"Error updating engine metrics: {e}")
    
    def get_strategies(self) -> Dict[str, BaseStrategy]:
        """Get all registered strategies"""
        with self._lock:
            return self._strategies.copy()
    
    def get_strategy(self, strategy_id: str) -> Optional[BaseStrategy]:
        """Get specific strategy"""
        with self._lock:
            return self._strategies.get(strategy_id)
    
    def get_signal_history(self, strategy_id: Optional[str] = None,
                          limit: Optional[int] = None) -> List[StrategySignal]:
        """Get signal history"""
        
        with self._lock:
            signals = self._signal_history
            
            if strategy_id:
                signals = [s for s in signals if s.strategy_id == strategy_id]
            
            if limit:
                signals = signals[-limit:]
            
            return signals.copy()
    
    def get_engine_metrics(self) -> Dict[str, Any]:
        """Get engine metrics"""
        
        with self._lock:
            metrics = self._engine_metrics.copy()
            
            # Add calculated metrics
            if metrics['uptime_start']:
                uptime = (datetime.now() - metrics['uptime_start']).total_seconds()
                metrics['uptime_seconds'] = uptime
                metrics['uptime_hours'] = uptime / 3600
            
            return metrics
    
    def get_engine_status(self) -> Dict[str, Any]:
        """Get comprehensive engine status"""
        
        with self._lock:
            strategy_states = {}
            for strategy_id, strategy in self._strategies.items():
                strategy_states[strategy_id] = strategy.get_state().value
            
            return {
                'execution_active': self._execution_active,
                'strategies_registered': len(self._strategies),
                'strategy_states': strategy_states,
                'signals_in_queue': len(self._signal_queue),
                'signal_processors': len(self._signal_processors),
                'last_data_update': self._last_data_update,
                'market_data_symbols': list(self._market_data_cache.keys()),
                'metrics': self.get_engine_metrics()
            }