"""
Strategy Engine - Core Strategy Execution System
Advanced strategy execution framework with lifecycle management and monitoring
"""

import logging
import pandas as pd
from datetime import datetime
from typing import Dict, List, Optional, Any, Callable
from dataclasses import dataclass, field
from enum import Enum
from abc import ABC, abstractmethod
import asyncio
import threading
import time
import warnings
from collections import deque
import uuid

# Import canonical types from type_definitions (Single Source of Truth)
from ...type_definitions.strategy import StrategyType, SignalType

# Import ISystemComponent for orchestrator integration
try:
    from ...system.interfaces import ISystemComponent
except ImportError:
    # Fallback definition
    class ISystemComponent(ABC):
        @abstractmethod
        async def initialize(self) -> bool:
            pass

        @abstractmethod
        async def start(self) -> bool:
            pass

        @abstractmethod
        async def stop(self) -> bool:
            pass

        @abstractmethod
        async def health_check(self) -> Dict[str, Any]:
            pass

        @abstractmethod
        def get_status(self) -> Dict[str, Any]:
            pass

warnings.filterwarnings('ignore')
logger = logging.getLogger(__name__)


class StrategyState(Enum):
    """Strategy execution states"""
    INACTIVE = "inactive"
    INITIALIZING = "initializing"
    ACTIVE = "active"
    PAUSED = "paused"
    STOPPING = "stopping"
    STOPPED = "stopped"
    ERROR = "error"
    WARMING_UP = "warming_up"


# StrategyType imported from type_definitions.strategy (canonical source)
# SignalType imported from type_definitions.strategy (canonical source)


class RiskLevel(Enum):
    """Risk levels for strategy execution"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class StrategySignal:
    """Trading signal generated by strategy"""

    # Signal identification
    signal_id: str = ""
    strategy_id: str = ""
    timestamp: datetime = field(default_factory=datetime.now)

    # Signal details
    symbol: str = ""
    signal_type: SignalType = SignalType.HOLD
    confidence: float = 0.0  # 0.0 to 1.0
    strength: float = 0.0    # Signal strength

    # Position sizing
    target_quantity: float = 0.0  # Absolute share quantity (if quantity_type is ABSOLUTE)
    target_weight: Optional[float] = None  # Portfolio weight/percentage (0.0-1.0) (if quantity_type is PERCENTAGE)
    quantity_type: str = "PERCENTAGE"  # "PERCENTAGE" or "ABSOLUTE" - indicates what target_quantity represents
    position_side: str = "long"  # long, short

    # Price information
    signal_price: Optional[float] = None
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None

    # Risk management
    max_position_size: Optional[float] = None
    risk_limit: Optional[float] = None
    holding_period: Optional[int] = None  # Expected holding period in minutes

    # Signal metadata
    signal_source: str = ""  # Which component generated this signal
    signal_reason: str = ""  # Why this signal was generated
    additional_data: Dict[str, Any] = field(default_factory=dict)

    # Execution tracking
    is_executed: bool = False
    execution_time: Optional[datetime] = None
    execution_price: Optional[float] = None
    execution_quantity: Optional[float] = None


@dataclass
class StrategyPosition:
    """Strategy position tracking"""

    # Position identification
    position_id: str = ""
    strategy_id: str = ""
    symbol: str = ""

    # Position details
    quantity: float = 0.0
    side: str = "long"  # long, short
    entry_price: float = 0.0
    current_price: float = 0.0
    market_value: float = 0.0

    # Risk management
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    max_loss: Optional[float] = None

    # Performance tracking
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    total_pnl: float = 0.0

    # Timing
    entry_time: datetime = field(default_factory=datetime.now)
    holding_period: int = 0  # Minutes
    last_update: datetime = field(default_factory=datetime.now)

    # Position metadata
    position_source: str = ""
    additional_data: Dict[str, Any] = field(default_factory=dict)


@dataclass
class StrategyMetrics:
    """Strategy performance metrics"""

    # Basic metrics
    total_signals: int = 0
    executed_signals: int = 0
    successful_signals: int = 0
    signal_success_rate: float = 0.0

    # Performance metrics
    total_return: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    max_drawdown: float = 0.0

    # Risk metrics
    sharpe_ratio: float = 0.0
    volatility: float = 0.0
    var_95: float = 0.0

    # Position metrics
    active_positions: int = 0
    total_positions: int = 0
    avg_holding_period: float = 0.0

    # Execution metrics
    avg_execution_time: float = 0.0
    slippage: float = 0.0
    transaction_costs: float = 0.0

    # Timing metrics
    last_signal_time: Optional[datetime] = None
    last_execution_time: Optional[datetime] = None
    strategy_uptime: float = 0.0  # Percentage

    # Error metrics
    error_count: int = 0
    warning_count: int = 0
    last_error_time: Optional[datetime] = None


@dataclass
class StrategyConfig:
    """Strategy configuration"""

    # Basic settings
    strategy_id: str = ""
    strategy_name: str = ""
    strategy_type: StrategyType = StrategyType.CUSTOM
    description: str = ""

    # Execution settings
    enable_live_trading: bool = False
    paper_trading_mode: bool = True
    max_positions: int = 10
    max_position_size: float = 0.1  # 10% of portfolio

    # Risk management
    max_daily_loss: float = 0.05    # 5% daily loss limit
    max_total_exposure: float = 1.0  # 100% exposure limit
    position_sizing_method: str = "fixed_percentage"
    risk_per_trade: float = 0.02    # 2% risk per trade

    # Signal settings
    min_signal_confidence: float = 0.6
    min_signal_strength: float = 0.5
    signal_timeout: int = 300  # 5 minutes

    # Data settings
    required_symbols: List[str] = field(default_factory=list)
    required_data_feeds: List[str] = field(default_factory=list)
    warmup_period: int = 100  # Number of data points for warmup

    # Performance settings
    benchmark_symbol: str = "SPY"
    performance_update_frequency: int = 60  # seconds
    enable_real_time_monitoring: bool = True

    # Strategy parameters (strategy-specific)
    strategy_parameters: Dict[str, Any] = field(default_factory=dict)

    # Execution settings
    execution_timeout: float = 30.0
    max_slippage: float = 0.001  # 0.1% max slippage
    enable_stop_loss: bool = True
    enable_take_profit: bool = True


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies

    Defines the interface that all strategies must implement.

    IMPORTANT: Position tracking is DEPRECATED in strategies.
    Use PositionBook (SSOT) for position state via Risk Manager.
    Strategies should focus on signal generation only.
    """

    def __init__(self, config: StrategyConfig):
        self.config = config
        self.strategy_id = config.strategy_id
        self.state = StrategyState.INACTIVE

        # Strategy data
        # DEPRECATED: self._positions is deprecated. Use PositionBook (SSOT) instead.
        # Position tracking should be handled by Risk Manager, not strategies.
        self._positions: Dict[str, StrategyPosition] = {}  # DEPRECATED
        self._signals: List[StrategySignal] = []
        self._metrics = StrategyMetrics()

        # Data storage
        self._market_data: Dict[str, pd.DataFrame] = {}
        self._indicators: Dict[str, pd.Series] = {}

        # Timing
        self._start_time: Optional[datetime] = None
        self._last_update: Optional[datetime] = None

        logger.info(f"Base strategy initialized: {self.strategy_id}")

    @abstractmethod
    def initialize(self) -> bool:
        """Initialize strategy - must be implemented by subclasses"""

    @abstractmethod
    def generate_signals(self, market_data: Dict[str, pd.DataFrame]) -> List[StrategySignal]:
        """
        Generate trading signals - must be implemented by subclasses.

        This is the PRIMARY responsibility of a strategy.
        """

    @abstractmethod
    def update_positions(self, market_data: Dict[str, pd.DataFrame]) -> None:
        """
        DEPRECATED: Update position tracking.

        Position tracking should be handled by PositionBook (SSOT) and Risk Manager.
        This method is kept for backward compatibility only.
        """

    def start(self) -> bool:
        """Start strategy execution"""
        try:
            if self.state != StrategyState.INACTIVE:
                logger.warning(f"Strategy {self.strategy_id} not in inactive state")
                return False

            self.state = StrategyState.INITIALIZING

            if not self.initialize():
                self.state = StrategyState.ERROR
                return False

            self.state = StrategyState.ACTIVE
            self._start_time = datetime.now()

            logger.info(f"Strategy {self.strategy_id} started successfully")
            return True

        except Exception as e:
            logger.error(f"Error starting strategy {self.strategy_id}: {e}")
            self.state = StrategyState.ERROR
            return False

    def stop(self) -> bool:
        """Stop strategy execution"""
        try:
            if self.state not in [StrategyState.ACTIVE, StrategyState.PAUSED]:
                logger.warning(f"Strategy {self.strategy_id} not in active/paused state")
                return False

            self.state = StrategyState.STOPPING

            # Close all positions if configured
            if hasattr(self.config, 'close_positions_on_stop') and self.config.close_positions_on_stop:
                self._close_all_positions()

            self.state = StrategyState.STOPPED

            logger.info(f"Strategy {self.strategy_id} stopped successfully")
            return True

        except Exception as e:
            logger.error(f"Error stopping strategy {self.strategy_id}: {e}")
            self.state = StrategyState.ERROR
            return False

    def pause(self) -> bool:
        """Pause strategy execution"""
        try:
            if self.state != StrategyState.ACTIVE:
                logger.warning(f"Strategy {self.strategy_id} not in active state")
                return False

            self.state = StrategyState.PAUSED
            logger.info(f"Strategy {self.strategy_id} paused")
            return True

        except Exception as e:
            logger.error(f"Error pausing strategy {self.strategy_id}: {e}")
            return False

    def resume(self) -> bool:
        """Resume strategy execution"""
        try:
            if self.state != StrategyState.PAUSED:
                logger.warning(f"Strategy {self.strategy_id} not in paused state")
                return False

            self.state = StrategyState.ACTIVE
            logger.info(f"Strategy {self.strategy_id} resumed")
            return True

        except Exception as e:
            logger.error(f"Error resuming strategy {self.strategy_id}: {e}")
            return False

    def update(self, market_data: Dict[str, pd.DataFrame]) -> List[StrategySignal]:
        """Update strategy with new market data"""
        try:
            logger.info(f"Strategy.update called, state: {self.state}")
            if self.state != StrategyState.ACTIVE:
                logger.warning(f"Strategy not active, returning empty signals. State: {self.state}")
                return []

            self._last_update = datetime.now()
            self._market_data.update(market_data)

            # Update positions
            self.update_positions(market_data)

            # Generate new signals
            new_signals = self.generate_signals(market_data)
            logger.info(f"Generated {len(new_signals)} signals")

            # Validate and filter signals
            valid_signals = self._validate_signals(new_signals)
            logger.info(f"Validated {len(valid_signals)} signals")

            # Update signals list
            self._signals.extend(valid_signals)

            # Update metrics
            self._update_metrics()

            return valid_signals

        except Exception as e:
            logger.error(f"Error updating strategy {self.strategy_id}: {e}")
            self._metrics.error_count += 1
            self._metrics.last_error_time = datetime.now()
            return []

    def _validate_signals(self, signals: List[StrategySignal]) -> List[StrategySignal]:
        """Validate generated signals"""
        valid_signals = []

        for signal in signals:
            # Check signal confidence
            if signal.confidence < self.config.min_signal_confidence:
                continue

            # Check signal strength
            if signal.strength < self.config.min_signal_strength:
                continue

            # Check position limits
            if len(self._positions) >= self.config.max_positions:
                continue

            # Check if signal is for existing position
            if signal.symbol in self._positions:
                # Handle position modification signals
                pass

            valid_signals.append(signal)

        return valid_signals

    def _close_all_positions(self) -> None:
        """Close all strategy positions"""
        try:
            for position in self._positions.values():
                # Generate close signal
                close_signal = StrategySignal(
                    signal_id=f"close_{position.position_id}",
                    strategy_id=self.strategy_id,
                    symbol=position.symbol,
                    signal_type=SignalType.CLOSE_LONG if position.side == "long" else SignalType.CLOSE_SHORT,
                    confidence=1.0,
                    strength=1.0,
                    target_quantity=abs(position.quantity),
                    signal_reason="Strategy stop - close all positions"
                )

                self._signals.append(close_signal)

            logger.info(f"Generated close signals for {len(self._positions)} positions")

        except Exception as e:
            logger.error(f"Error closing all positions: {e}")

    def _update_metrics(self) -> None:
        """Update strategy metrics"""
        try:
            # Basic metrics
            self._metrics.total_signals = len(self._signals)
            self._metrics.executed_signals = sum(1 for s in self._signals if s.is_executed)

            if self._metrics.total_signals > 0:
                self._metrics.signal_success_rate = self._metrics.executed_signals / self._metrics.total_signals

            # Position metrics
            self._metrics.active_positions = len(self._positions)

            # Performance metrics
            total_unrealized = sum(pos.unrealized_pnl for pos in self._positions.values())
            total_realized = sum(pos.realized_pnl for pos in self._positions.values())

            self._metrics.unrealized_pnl = total_unrealized
            self._metrics.realized_pnl = total_realized
            self._metrics.total_return = total_unrealized + total_realized

            # Timing metrics
            if self._signals:
                self._metrics.last_signal_time = max(s.timestamp for s in self._signals)

            if self._start_time:
                (datetime.now() - self._start_time).total_seconds()
                if self.state == StrategyState.ACTIVE:
                    self._metrics.strategy_uptime = 100.0
                else:
                    # Calculate actual uptime percentage
                    pass

        except Exception as e:
            logger.error(f"Error updating metrics: {e}")

    def get_positions(self) -> Dict[str, StrategyPosition]:
        """Get current strategy positions"""
        return self._positions.copy()

    def get_signals(self, limit: Optional[int] = None) -> List[StrategySignal]:
        """Get strategy signals"""
        if limit:
            return self._signals[-limit:]
        return self._signals.copy()

    def get_metrics(self) -> StrategyMetrics:
        """Get strategy metrics"""
        return self._metrics

    def get_state(self) -> StrategyState:
        """Get strategy state"""
        return self.state


class StrategyExecutionEngine(ISystemComponent):
    """
    Enhanced Strategy Execution Engine with ISystemComponent Integration

    Manages the execution lifecycle of trading strategies including
    initialization, data management, signal processing, and monitoring.
    Implements ISystemComponent for orchestrator integration.
    """

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        """Initialize enhanced strategy execution engine"""

        # Configuration
        self.config = config or {}
        self.max_concurrent_strategies = self.config.get('max_concurrent_strategies', 10)
        self.execution_interval = self.config.get('execution_interval', 1.0)
        self.enable_performance_monitoring = self.config.get('enable_performance_monitoring', True)
        self.enable_health_monitoring = self.config.get('enable_health_monitoring', True)

        # ISystemComponent state management
        self.component_id = str(uuid.uuid4())
        self.is_initialized = False
        self.is_operational = False
        self.last_error: Optional[str] = None
        self.initialization_time: Optional[datetime] = None
        self.start_time: Optional[datetime] = None

        # Orchestrator integration
        self.orchestrator: Optional[Any] = None  # HierarchicalSystemOrchestrator reference

        # Strategy management
        self._strategies: Dict[str, BaseStrategy] = {}
        self._strategy_configs: Dict[str, StrategyConfig] = {}

        # Execution control
        self._execution_active = False
        self._execution_thread: Optional[threading.Thread] = None
        self._stop_event = threading.Event()

        # Data management
        self._market_data_cache: Dict[str, pd.DataFrame] = {}
        self._last_data_update: Optional[datetime] = None

        # Signal management
        self._signal_queue: deque = deque()
        self._signal_history: List[StrategySignal] = []

        # Performance tracking
        self._engine_metrics = {
            'strategies_registered': 0,
            'strategies_active': 0,
            'total_signals_generated': 0,
            'total_signals_executed': 0,
            'execution_cycles': 0,
            'avg_cycle_time': 0.0,
            'errors': 0,
            'warnings': 0,
            'uptime_start': None,
            'last_update': None
        }

        # Thread safety
        self._lock = threading.RLock()

        # Signal processors
        self._signal_processors: List[Callable[[StrategySignal], bool]] = []

        # Component health tracking
        self.health_metrics = {
            'component_type': 'StrategyExecutionEngine',
            'initialization_status': 'pending',
            'operational_status': 'inactive',
            'last_health_check': None,
            'error_count': 0,
            'warning_count': 0,
            'performance_metrics': {
                'avg_cycle_time': 0.0,
                'total_cycles': 0,
                'successful_cycles': 0,
                'failed_cycles': 0
            }
        }

        logger.info(f"🚀 Enhanced Strategy Execution Engine initialized with component ID: {self.component_id}")

    # ========================================
    # ORCHESTRATOR INTEGRATION
    # ========================================

    def register_with_orchestrator(self, orchestrator) -> str:
        """Register component with HierarchicalSystemOrchestrator"""
        from core_engine.system.hierarchical_orchestrator import ComponentLayer, AuthorityLevel

        self.orchestrator = orchestrator
        self.component_id = orchestrator.register_component(
            name="StrategyExecutionEngine",
            component=self,
            layer=ComponentLayer.EXECUTION,
            authority_level=AuthorityLevel.OPERATIONAL,
            initialization_order=28  # After strategy manager
        )

        logger.info(f"✅ StrategyExecutionEngine registered with orchestrator: {self.component_id}")
        return self.component_id

    async def request_operation_authorization(self, operation: str, details: Dict[str, Any]) -> bool:
        """Request authorization from orchestrator for privileged operations"""
        if not self.orchestrator or not self.component_id:
            logger.warning("No orchestrator available for authorization request")
            return False

        return await self.orchestrator.request_system_authorization(
            operation, self.component_id, details
        )

    # ========================================
    # ISystemComponent Implementation
    # ========================================
    async def initialize(self) -> bool:
        """Initialize the strategy execution engine"""
        try:
            logger.info("🔄 Initializing Enhanced Strategy Execution Engine...")

            self.initialization_time = datetime.now()

            # Initialize internal components
            self._initialize_metrics()
            self._initialize_monitoring()

            # Validate configuration
            if not self._validate_configuration():
                self.last_error = "Configuration validation failed"
                return False

            # Initialize strategy registry integration
            await self._initialize_strategy_registry()

            # Initialize performance monitoring
            if self.enable_performance_monitoring:
                await self._initialize_performance_monitoring()

            self.is_initialized = True
            self.health_metrics['initialization_status'] = 'completed'

            logger.info("✅ Enhanced Strategy Execution Engine initialization complete")
            return True

        except Exception as e:
            self.last_error = str(e)
            self.health_metrics['initialization_status'] = 'failed'
            self.health_metrics['error_count'] += 1
            logger.error(f"❌ Strategy Execution Engine initialization failed: {e}")
            return False

    async def start(self) -> bool:
        """Start the strategy execution engine"""
        try:
            if not self.is_initialized:
                logger.error("❌ Cannot start - Strategy Execution Engine not initialized")
                return False

            logger.info("🚀 Starting Enhanced Strategy Execution Engine...")

            self.start_time = datetime.now()

            # Start execution engine
            if not self.start_execution():
                return False

            # Start health monitoring
            if self.enable_health_monitoring:
                await self._start_health_monitoring()

            self.is_operational = True
            self.health_metrics['operational_status'] = 'active'

            logger.info("✅ Enhanced Strategy Execution Engine started successfully")
            return True

        except Exception as e:
            self.last_error = str(e)
            self.health_metrics['error_count'] += 1
            logger.error(f"❌ Failed to start Strategy Execution Engine: {e}")
            return False

    async def stop(self) -> bool:
        """Stop the strategy execution engine"""
        try:
            logger.info("🛑 Stopping Enhanced Strategy Execution Engine...")

            # Stop execution engine
            if not self.stop_execution():
                logger.warning("⚠️ Issues stopping execution engine")

            # Stop health monitoring
            if hasattr(self, '_health_monitoring_task') and self._health_monitoring_task:
                self._health_monitoring_task.cancel()
                try:
                    await self._health_monitoring_task
                except asyncio.CancelledError:
                    pass

            self.is_operational = False
            self.health_metrics['operational_status'] = 'stopped'

            logger.info("✅ Enhanced Strategy Execution Engine stopped successfully")
            return True

        except Exception as e:
            self.last_error = str(e)
            self.health_metrics['error_count'] += 1
            logger.error(f"❌ Failed to stop Strategy Execution Engine: {e}")
            return False

    async def health_check(self) -> Dict[str, Any]:
        """Perform comprehensive health check"""
        try:
            health_status = {
                'healthy': True,
                'component_id': self.component_id,
                'component_type': 'StrategyExecutionEngine',
                'initialized': self.is_initialized,
                'operational': self.is_operational,
                'strategies_registered': len(self._strategies),
                'strategies_active': self._engine_metrics.get('strategies_active', 0),
                'execution_active': self._execution_active,
                'last_error': self.last_error,
                'uptime_seconds': 0,
                'performance_metrics': self.health_metrics['performance_metrics'].copy(),
                'error_count': self.health_metrics['error_count'],
                'warning_count': self.health_metrics['warning_count']
            }

            # Calculate uptime
            if self.start_time:
                uptime = (datetime.now() - self.start_time).total_seconds()
                health_status['uptime_seconds'] = uptime

            # Check strategy health
            unhealthy_strategies = []
            for strategy_id, strategy in self._strategies.items():
                try:
                    if hasattr(strategy, 'health_check'):
                        strategy_health = await strategy.health_check()
                        if not strategy_health.get('healthy', True):
                            unhealthy_strategies.append(strategy_id)
                except Exception as e:
                    unhealthy_strategies.append(strategy_id)
                    logger.warning(f"Health check failed for strategy {strategy_id}: {e}")

            if unhealthy_strategies:
                health_status['healthy'] = False
                health_status['unhealthy_strategies'] = unhealthy_strategies

            # Check execution thread health
            if self.is_operational and not self._execution_active:
                health_status['healthy'] = False
                health_status['warning'] = "Execution engine not active despite operational status"

            # Update health metrics
            self.health_metrics['last_health_check'] = datetime.now()

            return health_status

        except Exception as e:
            self.health_metrics['error_count'] += 1
            return {
                'healthy': False,
                'component_id': self.component_id,
                'component_type': 'StrategyExecutionEngine',
                'error': str(e)
            }

    def get_status(self) -> Dict[str, Any]:
        """Get current status of the strategy execution engine"""
        return {
            'component_id': self.component_id,
            'component_type': 'StrategyExecutionEngine',
            'initialized': self.is_initialized,
            'operational': self.is_operational,
            'execution_active': self._execution_active,
            'strategies_registered': len(self._strategies),
            'strategies_active': self._engine_metrics.get('strategies_active', 0),
            'signals_in_queue': len(self._signal_queue),
            'signal_processors': len(self._signal_processors),
            'last_data_update': self._last_data_update,
            'market_data_symbols': list(self._market_data_cache.keys()),
            'engine_metrics': self._engine_metrics.copy(),
            'health_metrics': self.health_metrics.copy(),
            'last_error': self.last_error,
            'initialization_time': self.initialization_time,
            'start_time': self.start_time
        }

    # Enhanced Strategy Management
    async def register_strategy(self, strategy: BaseStrategy, validate: bool = True) -> bool:
        """Register a strategy with enhanced validation and monitoring"""

        try:
            with self._lock:
                if strategy.strategy_id in self._strategies:
                    logger.warning(f"Strategy {strategy.strategy_id} already registered")
                    return False

                if len(self._strategies) >= self.max_concurrent_strategies:
                    logger.error(f"Maximum concurrent strategies ({self.max_concurrent_strategies}) reached")
                    return False

                # Enhanced validation
                if validate and not await self._validate_strategy(strategy):
                    logger.error(f"Strategy validation failed: {strategy.strategy_id}")
                    return False

                # Register strategy
                self._strategies[strategy.strategy_id] = strategy
                self._strategy_configs[strategy.strategy_id] = strategy.config

                # Initialize strategy monitoring
                await self._initialize_strategy_monitoring(strategy)

                self._engine_metrics['strategies_registered'] += 1

                logger.info(f"✅ Strategy {strategy.strategy_id} registered successfully with validation")
                return True

        except Exception as e:
            self.health_metrics['error_count'] += 1
            logger.error(f"❌ Error registering strategy {strategy.strategy_id}: {e}")
            return False

    def unregister_strategy(self, strategy_id: str) -> bool:
        """Unregister a strategy from the engine"""

        try:
            with self._lock:
                if strategy_id not in self._strategies:
                    logger.warning(f"Strategy {strategy_id} not found")
                    return False

                strategy = self._strategies[strategy_id]

                # Stop strategy if active
                if strategy.get_state() == StrategyState.ACTIVE:
                    strategy.stop()

                # Remove from engine
                del self._strategies[strategy_id]
                del self._strategy_configs[strategy_id]

                logger.info(f"Strategy {strategy_id} unregistered successfully")
                return True

        except Exception as e:
            logger.error(f"Error unregistering strategy {strategy_id}: {e}")
            return False

    def start_strategy(self, strategy_id: str) -> bool:
        """Start a specific strategy"""

        try:
            with self._lock:
                if strategy_id not in self._strategies:
                    logger.error(f"Strategy {strategy_id} not found")
                    return False

                strategy = self._strategies[strategy_id]
                result = strategy.start()

                if result:
                    self._engine_metrics['strategies_active'] += 1

                return result

        except Exception as e:
            logger.error(f"Error starting strategy {strategy_id}: {e}")
            return False

    def stop_strategy(self, strategy_id: str) -> bool:
        """Stop a specific strategy"""

        try:
            with self._lock:
                if strategy_id not in self._strategies:
                    logger.error(f"Strategy {strategy_id} not found")
                    return False

                strategy = self._strategies[strategy_id]
                result = strategy.stop()

                if result and self._engine_metrics['strategies_active'] > 0:
                    self._engine_metrics['strategies_active'] -= 1

                return result

        except Exception as e:
            logger.error(f"Error stopping strategy {strategy_id}: {e}")
            return False

    def start_all_strategies(self) -> Dict[str, bool]:
        """Start all registered strategies"""

        results = {}

        with self._lock:
            for strategy_id in self._strategies.keys():
                results[strategy_id] = self.start_strategy(strategy_id)

        successful = sum(1 for result in results.values() if result)
        logger.info(f"Started {successful}/{len(results)} strategies")

        return results

    def stop_all_strategies(self) -> Dict[str, bool]:
        """Stop all active strategies"""

        results = {}

        with self._lock:
            for strategy_id, strategy in self._strategies.items():
                if strategy.get_state() == StrategyState.ACTIVE:
                    results[strategy_id] = self.stop_strategy(strategy_id)

        logger.info(f"Stopped {len(results)} strategies")

        return results

    def start_execution(self) -> bool:
        """Start the execution engine"""

        try:
            if self._execution_active:
                logger.warning("Execution engine already running")
                return False

            self._execution_active = True
            self._stop_event.clear()

            # Start execution thread
            self._execution_thread = threading.Thread(
                target=self._execution_loop,
                daemon=True
            )
            self._execution_thread.start()

            self._engine_metrics['uptime_start'] = datetime.now()

            logger.info("Strategy execution engine started")
            return True

        except Exception as e:
            logger.error(f"Error starting execution engine: {e}")
            self._execution_active = False
            return False

    def stop_execution(self) -> bool:
        """Stop the execution engine"""

        try:
            if not self._execution_active:
                logger.warning("Execution engine not running")
                return False

            # Stop all strategies first
            self.stop_all_strategies()

            # Signal stop and wait for thread
            self._stop_event.set()
            self._execution_active = False

            if self._execution_thread and self._execution_thread.is_alive():
                self._execution_thread.join(timeout=5.0)

            logger.info("Strategy execution engine stopped")
            return True

        except Exception as e:
            logger.error(f"Error stopping execution engine: {e}")
            return False

    def update_market_data(self, symbol: str, data: pd.DataFrame) -> None:
        """Update market data for strategies"""

        try:
            with self._lock:
                self._market_data_cache[symbol] = data
                self._last_data_update = datetime.now()

        except Exception as e:
            logger.error(f"Error updating market data for {symbol}: {e}")

    def add_signal_processor(self, processor: Callable[[StrategySignal], bool]) -> None:
        """Add a signal processor function"""

        with self._lock:
            self._signal_processors.append(processor)

        logger.info("Signal processor added")

    def _execution_loop(self) -> None:
        """Main execution loop"""

        logger.info("Strategy execution loop started")

        while not self._stop_event.is_set() and self._execution_active:
            try:
                cycle_start = time.time()

                # Update all active strategies
                self._update_strategies()

                # Process signals
                self._process_signals()

                # Update engine metrics
                self._update_engine_metrics()

                # Calculate cycle time and update metrics
                cycle_time = time.time() - cycle_start
                self._update_cycle_metrics(cycle_time, True)

                # Update engine metrics
                self._engine_metrics['execution_cycles'] += 1
                total_time = (self._engine_metrics['avg_cycle_time'] *
                            (self._engine_metrics['execution_cycles'] - 1) + cycle_time)
                self._engine_metrics['avg_cycle_time'] = total_time / self._engine_metrics['execution_cycles']

                # Sleep to maintain reasonable cycle frequency
                sleep_time = max(0.1, self.execution_interval - cycle_time)
                time.sleep(sleep_time)

            except Exception as e:
                logger.error(f"Error in execution loop: {e}")
                self._engine_metrics['errors'] += 1
                time.sleep(1.0)  # Brief pause on error

        logger.info("Strategy execution loop stopped")

    def _update_cycle_metrics(self, cycle_time: float, success: bool) -> None:
        """Update cycle performance metrics"""
        try:
            perf_metrics = self.health_metrics['performance_metrics']
            perf_metrics['total_cycles'] += 1

            if success:
                perf_metrics['successful_cycles'] += 1
            else:
                perf_metrics['failed_cycles'] += 1

            # Update average cycle time
            current_avg = perf_metrics['avg_cycle_time']
            total_cycles = perf_metrics['total_cycles']
            perf_metrics['avg_cycle_time'] = ((current_avg * (total_cycles - 1)) + cycle_time) / total_cycles

        except Exception as e:
            logger.error(f"Error updating cycle metrics: {e}")

    def _update_strategies(self) -> None:
        """Update all active strategies with latest market data"""

        try:
            with self._lock:
                active_strategies = [
                    strategy for strategy in self._strategies.values()
                    if strategy.get_state() == StrategyState.ACTIVE
                ]

                if not active_strategies:
                    return

                # Update each strategy
                for strategy in active_strategies:
                    try:
                        # Filter market data for strategy's required symbols
                        strategy_data = {}
                        required_symbols = strategy.config.required_symbols

                        if required_symbols:
                            for symbol in required_symbols:
                                if symbol in self._market_data_cache:
                                    strategy_data[symbol] = self._market_data_cache[symbol]
                        else:
                            # Use all available data if no specific symbols required
                            strategy_data = self._market_data_cache.copy()

                        # Update strategy
                        new_signals = strategy.update(strategy_data)

                        # Add signals to queue
                        for signal in new_signals:
                            self._signal_queue.append(signal)
                            self._signal_history.append(signal)

                        self._engine_metrics['total_signals_generated'] += len(new_signals)

                    except Exception as e:
                        logger.error(f"Error updating strategy {strategy.strategy_id}: {e}")
                        self._engine_metrics['errors'] += 1

        except Exception as e:
            logger.error(f"Error in strategy update: {e}")
            self._engine_metrics['errors'] += 1

    def _process_signals(self) -> None:
        """Process signals in the signal queue"""

        try:
            while self._signal_queue:
                signal = self._signal_queue.popleft()

                # Process signal through registered processors
                processed = True
                for processor in self._signal_processors:
                    try:
                        if not processor(signal):
                            processed = False
                            break
                    except Exception as e:
                        logger.error(f"Error in signal processor: {e}")
                        processed = False
                        break

                if processed:
                    signal.is_executed = True
                    signal.execution_time = datetime.now()
                    self._engine_metrics['total_signals_executed'] += 1

        except Exception as e:
            logger.error(f"Error processing signals: {e}")
            self._engine_metrics['errors'] += 1

    def _update_engine_metrics(self) -> None:
        """Update engine metrics"""

        try:
            self._engine_metrics['last_update'] = datetime.now()

            # Count active strategies
            active_count = sum(
                1 for strategy in self._strategies.values()
                if strategy.get_state() == StrategyState.ACTIVE
            )
            self._engine_metrics['strategies_active'] = active_count

        except Exception as e:
            logger.error(f"Error updating engine metrics: {e}")

    def get_strategies(self) -> Dict[str, BaseStrategy]:
        """Get all registered strategies"""
        with self._lock:
            return self._strategies.copy()

    def get_strategy(self, strategy_id: str) -> Optional[BaseStrategy]:
        """Get specific strategy"""
        with self._lock:
            return self._strategies.get(strategy_id)

    def get_signal_history(self, strategy_id: Optional[str] = None,
                          limit: Optional[int] = None) -> List[StrategySignal]:
        """Get signal history"""

        with self._lock:
            signals = self._signal_history

            if strategy_id:
                signals = [s for s in signals if s.strategy_id == strategy_id]

            if limit:
                signals = signals[-limit:]

            return signals.copy()

    def get_engine_metrics(self) -> Dict[str, Any]:
        """Get engine metrics"""

        with self._lock:
            metrics = self._engine_metrics.copy()

            # Add calculated metrics
            if metrics['uptime_start']:
                uptime = (datetime.now() - metrics['uptime_start']).total_seconds()
                metrics['uptime_seconds'] = uptime
                metrics['uptime_hours'] = uptime / 3600

            return metrics

    def get_engine_status(self) -> Dict[str, Any]:
        """Get comprehensive engine status"""

        with self._lock:
            strategy_states = {}
            for strategy_id, strategy in self._strategies.items():
                strategy_states[strategy_id] = strategy.get_state().value

            return {
                'component_id': self.component_id,
                'component_type': 'StrategyExecutionEngine',
                'initialized': self.is_initialized,
                'operational': self.is_operational,
                'execution_active': self._execution_active,
                'strategies_registered': len(self._strategies),
                'strategy_states': strategy_states,
                'signals_in_queue': len(self._signal_queue),
                'signal_processors': len(self._signal_processors),
                'last_data_update': self._last_data_update,
                'market_data_symbols': list(self._market_data_cache.keys()),
                'metrics': self.get_engine_metrics(),
                'health_metrics': self.health_metrics.copy(),
                'last_error': self.last_error
            }

    # Enhanced Internal Methods
    def _initialize_metrics(self) -> None:
        """Initialize enhanced metrics tracking"""
        self._engine_metrics.update({
            'component_id': self.component_id,
            'initialization_time': datetime.now(),
            'health_checks_performed': 0,
            'validation_checks_performed': 0,
            'strategy_registrations_attempted': 0,
            'strategy_registrations_successful': 0
        })

    def _initialize_monitoring(self) -> None:
        """Initialize monitoring systems"""
        self._monitoring_active = False
        self._health_monitoring_task: Optional[asyncio.Task] = None
        self._performance_monitoring_task: Optional[asyncio.Task] = None

    def _validate_configuration(self) -> bool:
        """Validate engine configuration"""
        try:
            if self.max_concurrent_strategies <= 0:
                logger.error("max_concurrent_strategies must be positive")
                return False

            if self.execution_interval <= 0:
                logger.error("execution_interval must be positive")
                return False

            return True

        except Exception as e:
            logger.error(f"Configuration validation error: {e}")
            return False

    async def _initialize_strategy_registry(self) -> None:
        """Initialize strategy registry integration"""
        try:
            # Placeholder for strategy registry integration
            logger.info("📋 Strategy registry integration initialized")
        except Exception as e:
            logger.warning(f"Strategy registry initialization failed: {e}")

    async def _initialize_performance_monitoring(self) -> None:
        """Initialize performance monitoring"""
        try:
            logger.info("📊 Performance monitoring initialized")
        except Exception as e:
            logger.warning(f"Performance monitoring initialization failed: {e}")

    async def _start_health_monitoring(self) -> None:
        """Start health monitoring task"""
        try:
            self._health_monitoring_task = asyncio.create_task(self._health_monitoring_loop())
            logger.info("💓 Health monitoring started")
        except Exception as e:
            logger.warning(f"Health monitoring start failed: {e}")

    async def _health_monitoring_loop(self) -> None:
        """Health monitoring loop"""
        while self.is_operational:
            try:
                await self.health_check()
                self.health_metrics['health_checks_performed'] = self.health_metrics.get('health_checks_performed', 0) + 1
                await asyncio.sleep(30)  # Health check every 30 seconds
            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.error(f"Health monitoring error: {e}")
                await asyncio.sleep(60)  # Longer wait on error

    async def _validate_strategy(self, strategy: BaseStrategy) -> bool:
        """Enhanced strategy validation"""
        try:
            self._engine_metrics['validation_checks_performed'] += 1

            # Basic validation
            if not hasattr(strategy, 'strategy_id') or not strategy.strategy_id:
                logger.error("Strategy missing strategy_id")
                return False

            if not hasattr(strategy, 'initialize') or not callable(strategy.initialize):
                logger.error("Strategy missing initialize method")
                return False

            if not hasattr(strategy, 'update') or not callable(strategy.update):
                logger.error("Strategy missing update method")
                return False

            # Test initialization
            try:
                init_result = strategy.initialize()
                if not isinstance(init_result, bool):
                    logger.warning("Strategy initialize() should return boolean")
            except Exception as e:
                logger.error(f"Strategy initialization test failed: {e}")
                return False

            return True

        except Exception as e:
            logger.error(f"Strategy validation error: {e}")
            return False

    async def _initialize_strategy_monitoring(self, strategy: BaseStrategy) -> None:
        """Initialize monitoring for a specific strategy"""
        try:
            # Initialize strategy-specific metrics
            strategy_metrics = {
                'registration_time': datetime.now(),
                'total_updates': 0,
                'successful_updates': 0,
                'failed_updates': 0,
                'signals_generated': 0,
                'last_update_time': None,
                'avg_update_time': 0.0
            }

            # Store strategy metrics (could be expanded)
            if not hasattr(self, '_strategy_metrics'):
                self._strategy_metrics = {}

            self._strategy_metrics[strategy.strategy_id] = strategy_metrics

            logger.info(f"📊 Monitoring initialized for strategy: {strategy.strategy_id}")

        except Exception as e:
            logger.warning(f"Strategy monitoring initialization failed for {strategy.strategy_id}: {e}")