"""
Real-Time Monitoring System for Statistical Arbitrage Pairs
===========================================================

This module provides comprehensive real-time monitoring capabilities for statistical arbitrage pairs,
including correlation tracking, regime detection, and performance degradation alerts.

Key Features:
- Real-time pair relationship monitoring
- Correlation breakdown detection
- Regime change monitoring
- Performance degradation alerts
- Statistical analysis and trend detection
- Automated alert generation and notifications

Author: Pro Quant Desk Trader
Date: 2024
"""

import asyncio
import logging
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Tuple, Callable, Any
from dataclasses import dataclass, field
from enum import Enum
import json
import warnings
from concurrent.futures import ThreadPoolExecutor
import threading
import time
from collections import deque, defaultdict
import sqlite3
import os

# Statistical libraries
from scipy import stats
from scipy.signal import find_peaks
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class AlertSeverity(Enum):
    """Alert severity levels"""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class MonitoringStatus(Enum):
    """Monitoring system status"""
    STOPPED = "STOPPED"
    STARTING = "STARTING"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    ERROR = "ERROR"

class RegimeType(Enum):
    """Market regime types"""
    TRENDING = "TRENDING"
    MEAN_REVERTING = "MEAN_REVERTING"
    VOLATILE = "VOLATILE"
    STABLE = "STABLE"
    TRANSITIONAL = "TRANSITIONAL"

@dataclass
class PairMetrics:
    """Real-time metrics for a trading pair"""
    pair_id: str
    symbol1: str
    symbol2: str
    correlation: float
    rolling_correlation: List[float] = field(default_factory=list)
    spread: float = 0.0
    spread_zscore: float = 0.0
    volatility: float = 0.0
    volume_ratio: float = 1.0
    last_update: datetime = field(default_factory=datetime.now)
    
    # Statistical measures
    correlation_stability: float = 0.0
    trend_strength: float = 0.0
    mean_reversion_strength: float = 0.0
    regime: RegimeType = RegimeType.STABLE
    
    # Performance metrics
    pnl: float = 0.0
    sharpe_ratio: float = 0.0
    max_drawdown: float = 0.0
    win_rate: float = 0.0
    
    # Risk metrics
    var_95: float = 0.0
    expected_shortfall: float = 0.0
    correlation_risk: float = 0.0

@dataclass
class MonitoringAlert:
    """Alert generated by monitoring system"""
    alert_id: str
    pair_id: str
    alert_type: str
    severity: AlertSeverity
    message: str
    timestamp: datetime
    metrics: Dict[str, Any]
    action_required: bool = False
    acknowledged: bool = False

@dataclass
class RegimeChangeEvent:
    """Regime change detection event"""
    pair_id: str
    old_regime: RegimeType
    new_regime: RegimeType
    confidence: float
    timestamp: datetime
    trigger_metrics: Dict[str, Any]
    expected_duration: Optional[timedelta] = None

class RealTimeMonitor:
    """
    Real-time monitoring system for statistical arbitrage pairs
    
    This class provides comprehensive monitoring capabilities including:
    - Correlation tracking and breakdown detection
    - Regime change monitoring
    - Performance degradation alerts
    - Statistical analysis and trend detection
    """
    
    def __init__(self, 
                 update_interval: int = 60,  # seconds
                 correlation_window: int = 50,
                 alert_threshold: float = 0.05,
                 db_path: str = "monitoring.db"):
        """
        Initialize the real-time monitoring system
        
        Args:
            update_interval: Update frequency in seconds
            correlation_window: Rolling window for correlation calculation
            alert_threshold: Threshold for generating alerts
            db_path: Path to SQLite database for storing monitoring data
        """
        self.update_interval = update_interval
        self.correlation_window = correlation_window
        self.alert_threshold = alert_threshold
        self.db_path = db_path
        
        # Monitoring state
        self.status = MonitoringStatus.STOPPED
        self.pair_metrics: Dict[str, PairMetrics] = {}
        self.alerts: List[MonitoringAlert] = []
        self.regime_events: List[RegimeChangeEvent] = []
        
        # Data storage
        self.price_data: Dict[str, deque] = defaultdict(lambda: deque(maxlen=1000))
        self.spread_data: Dict[str, deque] = defaultdict(lambda: deque(maxlen=1000))
        self.correlation_history: Dict[str, deque] = defaultdict(lambda: deque(maxlen=500))
        
        # Threading
        self.monitor_thread: Optional[threading.Thread] = None
        self.stop_event = threading.Event()
        self.lock = threading.Lock()
        
        # Alert callbacks
        self.alert_callbacks: List[Callable[[MonitoringAlert], None]] = []
        self.regime_callbacks: List[Callable[[RegimeChangeEvent], None]] = []
        
        # Initialize database
        self._init_database()
        
        logger.info(f"Real-time monitor initialized with {update_interval}s update interval")
    
    def _init_database(self):
        """Initialize SQLite database for monitoring data"""
        try:
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()
            
            # Create tables
            cursor.execute('''
                CREATE TABLE IF NOT EXISTS pair_metrics (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    pair_id TEXT NOT NULL,
                    timestamp DATETIME NOT NULL,
                    correlation REAL,
                    spread REAL,
                    spread_zscore REAL,
                    volatility REAL,
                    regime TEXT,
                    pnl REAL,
                    sharpe_ratio REAL,
                    max_drawdown REAL
                )
            ''')
            
            cursor.execute('''
                CREATE TABLE IF NOT EXISTS alerts (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    alert_id TEXT UNIQUE NOT NULL,
                    pair_id TEXT NOT NULL,
                    alert_type TEXT NOT NULL,
                    severity TEXT NOT NULL,
                    message TEXT NOT NULL,
                    timestamp DATETIME NOT NULL,
                    metrics TEXT,
                    acknowledged BOOLEAN DEFAULT FALSE
                )
            ''')
            
            cursor.execute('''
                CREATE TABLE IF NOT EXISTS regime_events (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    pair_id TEXT NOT NULL,
                    old_regime TEXT NOT NULL,
                    new_regime TEXT NOT NULL,
                    confidence REAL NOT NULL,
                    timestamp DATETIME NOT NULL,
                    trigger_metrics TEXT
                )
            ''')
            
            conn.commit()
            conn.close()
            logger.info("Database initialized successfully")
            
        except Exception as e:
            logger.error(f"Failed to initialize database: {e}")
            raise
    
    def add_pair(self, pair_id: str, symbol1: str, symbol2: str):
        """Add a pair to monitoring"""
        with self.lock:
            if pair_id not in self.pair_metrics:
                self.pair_metrics[pair_id] = PairMetrics(
                    pair_id=pair_id,
                    symbol1=symbol1,
                    symbol2=symbol2,
                    correlation=0.0
                )
                logger.info(f"Added pair {pair_id} to monitoring")
            else:
                logger.warning(f"Pair {pair_id} already being monitored")
    
    def remove_pair(self, pair_id: str):
        """Remove a pair from monitoring"""
        with self.lock:
            if pair_id in self.pair_metrics:
                del self.pair_metrics[pair_id]
                # Clean up data
                if pair_id in self.price_data:
                    del self.price_data[pair_id]
                if pair_id in self.spread_data:
                    del self.spread_data[pair_id]
                if pair_id in self.correlation_history:
                    del self.correlation_history[pair_id]
                logger.info(f"Removed pair {pair_id} from monitoring")
    
    def update_price_data(self, pair_id: str, price1: float, price2: float, timestamp: datetime = None):
        """Update price data for a pair"""
        if timestamp is None:
            timestamp = datetime.now()
        
        with self.lock:
            if pair_id in self.pair_metrics:
                self.price_data[pair_id].append({
                    'timestamp': timestamp,
                    'price1': price1,
                    'price2': price2
                })
                
                # Update metrics
                self._update_pair_metrics(pair_id)
    
    def _update_pair_metrics(self, pair_id: str):
        """Update all metrics for a pair"""
        try:
            metrics = self.pair_metrics[pair_id]
            price_data = list(self.price_data[pair_id])
            
            if len(price_data) < 2:
                return
            
            # Extract price series
            prices1 = np.array([d['price1'] for d in price_data])
            prices2 = np.array([d['price2'] for d in price_data])
            
            # Calculate correlation
            if len(prices1) >= self.correlation_window:
                correlation = np.corrcoef(prices1[-self.correlation_window:], 
                                       prices2[-self.correlation_window:])[0, 1]
                metrics.correlation = correlation if not np.isnan(correlation) else 0.0
                
                # Update rolling correlation
                metrics.rolling_correlation.append(metrics.correlation)
                if len(metrics.rolling_correlation) > 100:
                    metrics.rolling_correlation.pop(0)
            
            # Calculate spread and z-score
            if len(prices1) >= 20:
                # Simple spread calculation (can be enhanced with cointegration)
                spread = prices1 - prices2
                metrics.spread = spread[-1]
                
                spread_mean = np.mean(spread[-20:])
                spread_std = np.std(spread[-20:])
                if spread_std > 0:
                    metrics.spread_zscore = (spread[-1] - spread_mean) / spread_std
                
                self.spread_data[pair_id].append({
                    'timestamp': price_data[-1]['timestamp'],
                    'spread': metrics.spread,
                    'zscore': metrics.spread_zscore
                })
            
            # Calculate volatility
            if len(prices1) >= 20:
                returns1 = np.diff(np.log(prices1[-20:]))
                returns2 = np.diff(np.log(prices2[-20:]))
                spread_returns = returns1 - returns2
                metrics.volatility = np.std(spread_returns) * np.sqrt(252)  # Annualized
            
            # Update correlation stability
            if len(metrics.rolling_correlation) >= 10:
                metrics.correlation_stability = 1.0 - np.std(metrics.rolling_correlation[-10:])
            
            # Detect regime
            metrics.regime = self._detect_regime(pair_id)
            
            # Update risk metrics
            self._update_risk_metrics(pair_id)
            
            # Check for alerts
            self._check_alerts(pair_id)
            
            metrics.last_update = datetime.now()
            
        except Exception as e:
            logger.error(f"Error updating metrics for {pair_id}: {e}")
    
    def _detect_regime(self, pair_id: str) -> RegimeType:
        """Detect current market regime for a pair"""
        try:
            spread_data = list(self.spread_data[pair_id])
            if len(spread_data) < 50:
                return RegimeType.STABLE
            
            spreads = np.array([d['spread'] for d in spread_data[-50:]])
            
            # Calculate regime indicators
            volatility = np.std(spreads)
            trend_strength = abs(stats.linregress(range(len(spreads)), spreads)[0])
            mean_reversion = self._calculate_mean_reversion_strength(spreads)
            
            # Regime classification
            if volatility > np.percentile(spreads, 80):
                return RegimeType.VOLATILE
            elif trend_strength > 0.1:
                return RegimeType.TRENDING
            elif mean_reversion > 0.7:
                return RegimeType.MEAN_REVERTING
            elif volatility < np.percentile(spreads, 20):
                return RegimeType.STABLE
            else:
                return RegimeType.TRANSITIONAL
                
        except Exception as e:
            logger.error(f"Error detecting regime for {pair_id}: {e}")
            return RegimeType.STABLE
    
    def _calculate_mean_reversion_strength(self, spreads: np.ndarray) -> float:
        """Calculate mean reversion strength using Hurst exponent"""
        try:
            if len(spreads) < 20:
                return 0.0
            
            # Calculate Hurst exponent
            lags = range(2, min(20, len(spreads)//2))
            tau = [np.sqrt(np.std(np.subtract(spreads[lag:], spreads[:-lag]))) for lag in lags]
            
            if len(tau) < 2:
                return 0.0
            
            poly = np.polyfit(np.log(lags), np.log(tau), 1)
            hurst = poly[0]
            
            # Convert to mean reversion strength (0-1 scale)
            return max(0.0, min(1.0, 1.0 - 2.0 * hurst))
            
        except Exception as e:
            logger.error(f"Error calculating mean reversion strength: {e}")
            return 0.0
    
    def _update_risk_metrics(self, pair_id: str):
        """Update risk metrics for a pair"""
        try:
            metrics = self.pair_metrics[pair_id]
            spread_data = list(self.spread_data[pair_id])
            
            if len(spread_data) < 20:
                return
            
            spreads = np.array([d['spread'] for d in spread_data[-100:]])
            
            # Calculate VaR (95% confidence)
            metrics.var_95 = np.percentile(spreads, 5)
            
            # Calculate Expected Shortfall
            var_threshold = metrics.var_95
            tail_losses = spreads[spreads <= var_threshold]
            if len(tail_losses) > 0:
                metrics.expected_shortfall = np.mean(tail_losses)
            
            # Calculate correlation risk
            if len(metrics.rolling_correlation) >= 10:
                corr_volatility = np.std(metrics.rolling_correlation[-10:])
                metrics.correlation_risk = min(1.0, corr_volatility * 10)  # Scale to 0-1
            
        except Exception as e:
            logger.error(f"Error updating risk metrics for {pair_id}: {e}")
    
    def _check_alerts(self, pair_id: str):
        """Check for alert conditions"""
        try:
            metrics = self.pair_metrics[pair_id]
            
            # Correlation breakdown alert
            if abs(metrics.correlation) < 0.3 and metrics.correlation_stability < 0.5:
                self._generate_alert(
                    pair_id=pair_id,
                    alert_type="CORRELATION_BREAKDOWN",
                    severity=AlertSeverity.HIGH,
                    message=f"Correlation breakdown detected: {metrics.correlation:.3f}",
                    metrics_data={
                        'correlation': metrics.correlation,
                        'stability': metrics.correlation_stability
                    }
                )
            
            # High volatility alert
            if metrics.volatility > 0.5:  # 50% annualized volatility
                self._generate_alert(
                    pair_id=pair_id,
                    alert_type="HIGH_VOLATILITY",
                    severity=AlertSeverity.MEDIUM,
                    message=f"High volatility detected: {metrics.volatility:.3f}",
                    metrics_data={'volatility': metrics.volatility}
                )
            
            # Extreme spread alert
            if abs(metrics.spread_zscore) > 3:
                severity = AlertSeverity.CRITICAL if abs(metrics.spread_zscore) > 4 else AlertSeverity.HIGH
                self._generate_alert(
                    pair_id=pair_id,
                    alert_type="EXTREME_SPREAD",
                    severity=severity,
                    message=f"Extreme spread detected: {metrics.spread_zscore:.3f}σ",
                    metrics_data={'zscore': metrics.spread_zscore}
                )
            
            # Regime change alert
            current_regime = metrics.regime
            if hasattr(self, '_last_regime') and pair_id in self._last_regime:
                if self._last_regime[pair_id] != current_regime:
                    self._generate_regime_change_event(pair_id, self._last_regime[pair_id], current_regime)
            
            if not hasattr(self, '_last_regime'):
                self._last_regime = {}
            self._last_regime[pair_id] = current_regime
            
        except Exception as e:
            logger.error(f"Error checking alerts for {pair_id}: {e}")
    
    def _generate_alert(self, pair_id: str, alert_type: str, severity: AlertSeverity, 
                       message: str, metrics_data: Dict[str, Any]):
        """Generate and store an alert"""
        try:
            alert = MonitoringAlert(
                alert_id=f"{pair_id}_{alert_type}_{int(time.time())}",
                pair_id=pair_id,
                alert_type=alert_type,
                severity=severity,
                message=message,
                timestamp=datetime.now(),
                metrics=metrics_data,
                action_required=severity in [AlertSeverity.HIGH, AlertSeverity.CRITICAL]
            )
            
            self.alerts.append(alert)
            
            # Store in database
            self._store_alert(alert)
            
            # Notify callbacks
            for callback in self.alert_callbacks:
                try:
                    callback(alert)
                except Exception as e:
                    logger.error(f"Error in alert callback: {e}")
            
            logger.warning(f"Alert generated: {alert.alert_type} for {pair_id} - {message}")
            
        except Exception as e:
            logger.error(f"Error generating alert: {e}")
    
    def _generate_regime_change_event(self, pair_id: str, old_regime: RegimeType, new_regime: RegimeType):
        """Generate regime change event"""
        try:
            event = RegimeChangeEvent(
                pair_id=pair_id,
                old_regime=old_regime,
                new_regime=new_regime,
                confidence=0.8,  # Can be enhanced with ML confidence
                timestamp=datetime.now(),
                trigger_metrics={}
            )
            
            self.regime_events.append(event)
            
            # Store in database
            self._store_regime_event(event)
            
            # Notify callbacks
            for callback in self.regime_callbacks:
                try:
                    callback(event)
                except Exception as e:
                    logger.error(f"Error in regime callback: {e}")
            
            logger.info(f"Regime change detected for {pair_id}: {old_regime.value} -> {new_regime.value}")
            
        except Exception as e:
            logger.error(f"Error generating regime change event: {e}")
    
    def _store_alert(self, alert: MonitoringAlert):
        """Store alert in database"""
        try:
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()
            
            cursor.execute('''
                INSERT OR REPLACE INTO alerts 
                (alert_id, pair_id, alert_type, severity, message, timestamp, metrics, acknowledged)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            ''', (
                alert.alert_id,
                alert.pair_id,
                alert.alert_type,
                alert.severity.value,
                alert.message,
                alert.timestamp,
                json.dumps(alert.metrics),
                alert.acknowledged
            ))
            
            conn.commit()
            conn.close()
            
        except Exception as e:
            logger.error(f"Error storing alert: {e}")
    
    def _store_regime_event(self, event: RegimeChangeEvent):
        """Store regime change event in database"""
        try:
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()
            
            cursor.execute('''
                INSERT INTO regime_events 
                (pair_id, old_regime, new_regime, confidence, timestamp, trigger_metrics)
                VALUES (?, ?, ?, ?, ?, ?)
            ''', (
                event.pair_id,
                event.old_regime.value,
                event.new_regime.value,
                event.confidence,
                event.timestamp,
                json.dumps(event.trigger_metrics)
            ))
            
            conn.commit()
            conn.close()
            
        except Exception as e:
            logger.error(f"Error storing regime event: {e}")
    
    def start_monitoring(self):
        """Start the monitoring system"""
        if self.status == MonitoringStatus.RUNNING:
            logger.warning("Monitoring already running")
            return
        
        self.status = MonitoringStatus.STARTING
        self.stop_event.clear()
        
        self.monitor_thread = threading.Thread(target=self._monitoring_loop, daemon=True)
        self.monitor_thread.start()
        
        self.status = MonitoringStatus.RUNNING
        logger.info("Real-time monitoring started")
    
    def stop_monitoring(self):
        """Stop the monitoring system"""
        if self.status != MonitoringStatus.RUNNING:
            logger.warning("Monitoring not running")
            return
        
        self.stop_event.set()
        if self.monitor_thread:
            self.monitor_thread.join(timeout=5)
        
        self.status = MonitoringStatus.STOPPED
        logger.info("Real-time monitoring stopped")
    
    def _monitoring_loop(self):
        """Main monitoring loop"""
        logger.info("Monitoring loop started")
        
        while not self.stop_event.is_set():
            try:
                start_time = time.time()
                
                # Update all pair metrics
                with self.lock:
                    for pair_id in list(self.pair_metrics.keys()):
                        self._update_pair_metrics(pair_id)
                
                # Store metrics in database
                self._store_current_metrics()
                
                # Clean up old data
                self._cleanup_old_data()
                
                # Calculate sleep time
                elapsed = time.time() - start_time
                sleep_time = max(0, self.update_interval - elapsed)
                
                if sleep_time > 0:
                    self.stop_event.wait(sleep_time)
                
            except Exception as e:
                logger.error(f"Error in monitoring loop: {e}")
                self.stop_event.wait(1)  # Wait 1 second before retrying
        
        logger.info("Monitoring loop stopped")
    
    def _store_current_metrics(self):
        """Store current metrics in database"""
        try:
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()
            
            for pair_id, metrics in self.pair_metrics.items():
                cursor.execute('''
                    INSERT INTO pair_metrics 
                    (pair_id, timestamp, correlation, spread, spread_zscore, volatility, 
                     regime, pnl, sharpe_ratio, max_drawdown)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ''', (
                    pair_id,
                    datetime.now(),
                    metrics.correlation,
                    metrics.spread,
                    metrics.spread_zscore,
                    metrics.volatility,
                    metrics.regime.value,
                    metrics.pnl,
                    metrics.sharpe_ratio,
                    metrics.max_drawdown
                ))
            
            conn.commit()
            conn.close()
            
        except Exception as e:
            logger.error(f"Error storing metrics: {e}")
    
    def _cleanup_old_data(self):
        """Clean up old data to prevent memory issues"""
        try:
            cutoff_time = datetime.now() - timedelta(hours=24)
            
            # Clean up alerts older than 24 hours
            self.alerts = [alert for alert in self.alerts if alert.timestamp > cutoff_time]
            
            # Clean up regime events older than 24 hours
            self.regime_events = [event for event in self.regime_events if event.timestamp > cutoff_time]
            
        except Exception as e:
            logger.error(f"Error cleaning up old data: {e}")
    
    def get_pair_status(self, pair_id: str) -> Optional[PairMetrics]:
        """Get current status of a pair"""
        with self.lock:
            return self.pair_metrics.get(pair_id)
    
    def get_recent_alerts(self, hours: int = 24) -> List[MonitoringAlert]:
        """Get recent alerts"""
        cutoff_time = datetime.now() - timedelta(hours=hours)
        return [alert for alert in self.alerts if alert.timestamp > cutoff_time]
    
    def get_regime_events(self, pair_id: str = None, hours: int = 24) -> List[RegimeChangeEvent]:
        """Get regime change events"""
        cutoff_time = datetime.now() - timedelta(hours=hours)
        events = [event for event in self.regime_events if event.timestamp > cutoff_time]
        
        if pair_id:
            events = [event for event in events if event.pair_id == pair_id]
        
        return events
    
    def add_alert_callback(self, callback: Callable[[MonitoringAlert], None]):
        """Add callback for alert notifications"""
        self.alert_callbacks.append(callback)
    
    def add_regime_callback(self, callback: Callable[[RegimeChangeEvent], None]):
        """Add callback for regime change notifications"""
        self.regime_callbacks.append(callback)
    
    def acknowledge_alert(self, alert_id: str):
        """Acknowledge an alert"""
        for alert in self.alerts:
            if alert.alert_id == alert_id:
                alert.acknowledged = True
                
                # Update database
                try:
                    conn = sqlite3.connect(self.db_path)
                    cursor = conn.cursor()
                    cursor.execute('UPDATE alerts SET acknowledged = TRUE WHERE alert_id = ?', (alert_id,))
                    conn.commit()
                    conn.close()
                except Exception as e:
                    logger.error(f"Error acknowledging alert: {e}")
                
                logger.info(f"Alert {alert_id} acknowledged")
                break
    
    def get_monitoring_summary(self) -> Dict[str, Any]:
        """Get comprehensive monitoring summary"""
        with self.lock:
            summary = {
                'status': self.status.value,
                'pairs_monitored': len(self.pair_metrics),
                'active_alerts': len([a for a in self.alerts if not a.acknowledged]),
                'recent_regime_changes': len(self.get_regime_events(hours=24)),
                'last_update': datetime.now().isoformat(),
                'pairs': {}
            }
            
            for pair_id, metrics in self.pair_metrics.items():
                summary['pairs'][pair_id] = {
                    'correlation': metrics.correlation,
                    'spread_zscore': metrics.spread_zscore,
                    'volatility': metrics.volatility,
                    'regime': metrics.regime.value,
                    'correlation_stability': metrics.correlation_stability,
                    'last_update': metrics.last_update.isoformat()
                }
            
            return summary

# Example usage and testing
if __name__ == "__main__":
    # Create monitoring system
    monitor = RealTimeMonitor(update_interval=30)
    
    # Add alert callback
    def alert_handler(alert: MonitoringAlert):
        print(f"ALERT: {alert.alert_type} - {alert.message}")
    
    monitor.add_alert_callback(alert_handler)
    
    # Add some pairs
    monitor.add_pair("TSLA_NVDA", "TSLA", "NVDA")
    monitor.add_pair("QQQ_TQQQ", "QQQ", "TQQQ")
    
    # Start monitoring
    monitor.start_monitoring()
    
    # Simulate some price updates
    import random
    for i in range(100):
        monitor.update_price_data("TSLA_NVDA", 100 + random.random() * 10, 200 + random.random() * 20)
        monitor.update_price_data("QQQ_TQQQ", 300 + random.random() * 5, 600 + random.random() * 10)
        time.sleep(1)
    
    # Get summary
    summary = monitor.get_monitoring_summary()
    print(json.dumps(summary, indent=2))
    
    # Stop monitoring
    monitor.stop_monitoring() 