"""
Enhanced Pair Backtester Interfaces
==================================

This module provides the foundational interface definitions for the enhanced
pair backtester system. These interfaces establish clear boundaries between
system layers and ensure proper separation of concerns.

Author: Professional Trading System Architecture
Version: 1.0.0
"""

from abc import ABC, abstractmethod
from typing import Dict, List, Any, Optional, Union
from dataclasses import dataclass
from enum import Enum
import pandas as pd


class SignalType(Enum):
    """Enumeration of trading signal types."""
    LONG = "LONG"
    SHORT = "SHORT"
    CLOSE_LONG = "CLOSE_LONG"
    CLOSE_SHORT = "CLOSE_SHORT"
    HOLD = "HOLD"


class OrderType(Enum):
    """Enumeration of order types."""
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"


@dataclass
class TradingSignal:
    """
    Standardized trading signal representation.
    
    This is the universal format for all trading signals generated by
    strategies and consumed by the execution engine.
    """
    symbol: str
    signal_type: SignalType
    confidence: float  # 0.0 to 1.0
    timestamp: pd.Timestamp
    price_target: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    position_size: Optional[float] = None
    metadata: Optional[Dict[str, Any]] = None
    
    def __post_init__(self):
        """Validate signal data."""
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(f"Confidence must be between 0.0 and 1.0, got {self.confidence}")
        
        if self.position_size is not None and self.position_size <= 0:
            raise ValueError(f"Position size must be positive, got {self.position_size}")


@dataclass
class RawSignal:
    """
    Raw signal data from strategy calculations.
    
    This represents the unprocessed output from strategy calculations
    before conversion to standardized trading signals.
    """
    symbol: str
    value: float
    confidence: float
    signal_metadata: Dict[str, Any]
    timestamp: pd.Timestamp


class StrategyInterface(ABC):
    """
    Abstract interface for all trading strategies.
    
    This interface defines the contract that all strategies must implement.
    Strategies are responsible for generating raw signals based on market data.
    They should NOT contain portfolio management or execution logic.
    """
    
    @abstractmethod
    def calculate_signals(self, market_data: pd.DataFrame) -> List[RawSignal]:
        """
        Calculate raw trading signals based on market data.
        
        Args:
            market_data: DataFrame containing OHLCV data and any additional features
            
        Returns:
            List of RawSignal objects containing strategy calculations
            
        Note:
            This method should be PURE - no side effects, no portfolio access,
            no execution logic. Only signal generation based on market data.
        """
        pass
    
    @abstractmethod
    def get_strategy_name(self) -> str:
        """Return the unique name of this strategy."""
        pass
    
    @abstractmethod
    def get_required_indicators(self) -> List[str]:
        """
        Return list of required technical indicators.
        
        Returns:
            List of indicator names that must be present in market_data
        """
        pass
    
    @abstractmethod
    def validate_parameters(self, parameters: Dict[str, Any]) -> bool:
        """
        Validate strategy parameters.
        
        Args:
            parameters: Dictionary of strategy parameters
            
        Returns:
            True if parameters are valid, raises ValueError otherwise
        """
        pass


class PortfolioInterface(ABC):
    """
    Abstract interface for portfolio management operations.
    
    This interface defines portfolio-related operations including position
    tracking, risk management, and portfolio metrics calculation.
    """
    
    @abstractmethod
    def get_current_positions(self) -> Dict[str, float]:
        """
        Get current portfolio positions.
        
        Returns:
            Dictionary mapping symbol to position size (positive for long, negative for short)
        """
        pass
    
    @abstractmethod
    def calculate_position_size(self, signal: TradingSignal, portfolio_value: float) -> float:
        """
        Calculate appropriate position size for a trading signal.
        
        Args:
            signal: Trading signal to size
            portfolio_value: Current portfolio value
            
        Returns:
            Position size in shares/contracts
        """
        pass
    
    @abstractmethod
    def check_risk_limits(self, signal: TradingSignal, current_positions: Dict[str, float]) -> bool:
        """
        Check if executing a signal would violate risk limits.
        
        Args:
            signal: Trading signal to check
            current_positions: Current portfolio positions
            
        Returns:
            True if signal is within risk limits, False otherwise
        """
        pass
    
    @abstractmethod
    def update_portfolio(self, executed_orders: List[Dict[str, Any]]) -> None:
        """
        Update portfolio state with executed orders.
        
        Args:
            executed_orders: List of executed order dictionaries
        """
        pass


class ExecutionInterface(ABC):
    """
    Abstract interface for order execution operations.
    
    This interface defines the contract for executing trading orders
    and managing order lifecycle.
    """
    
    @abstractmethod
    def execute_signal(self, signal: TradingSignal, current_price: float) -> Dict[str, Any]:
        """
        Execute a trading signal.
        
        Args:
            signal: Trading signal to execute
            current_price: Current market price for the symbol
            
        Returns:
            Dictionary containing execution details
        """
        pass
    
    @abstractmethod
    def get_execution_cost(self, symbol: str, quantity: float, order_type: OrderType) -> float:
        """
        Calculate execution cost for an order.
        
        Args:
            symbol: Trading symbol
            quantity: Order quantity
            order_type: Type of order
            
        Returns:
            Estimated execution cost (commission + slippage)
        """
        pass
    
    @abstractmethod
    def validate_order(self, signal: TradingSignal) -> bool:
        """
        Validate if an order can be executed.
        
        Args:
            signal: Trading signal to validate
            
        Returns:
            True if order is valid for execution
        """
        pass


class SignalConverterInterface(ABC):
    """
    Abstract interface for converting raw signals to trading signals.
    
    This interface handles the conversion from strategy-specific raw signals
    to standardized trading signals that can be consumed by the execution engine.
    """
    
    @abstractmethod
    def convert_to_trading_signals(self, raw_signals: List[RawSignal]) -> List[TradingSignal]:
        """
        Convert raw signals to standardized trading signals.
        
        Args:
            raw_signals: List of raw signals from strategies
            
        Returns:
            List of standardized trading signals
        """
        pass
    
    @abstractmethod
    def apply_signal_filters(self, signals: List[TradingSignal]) -> List[TradingSignal]:
        """
        Apply filtering logic to trading signals.
        
        Args:
            signals: List of trading signals to filter
            
        Returns:
            Filtered list of trading signals
        """
        pass


class ConfigurationInterface(ABC):
    """
    Abstract interface for configuration management.
    
    This interface provides centralized configuration management for all
    system components.
    """
    
    @abstractmethod
    def get_strategy_config(self, strategy_name: str) -> Dict[str, Any]:
        """Get configuration for a specific strategy."""
        pass
    
    @abstractmethod
    def get_risk_config(self) -> Dict[str, Any]:
        """Get risk management configuration."""
        pass
    
    @abstractmethod
    def get_execution_config(self) -> Dict[str, Any]:
        """Get execution engine configuration."""
        pass
    
    @abstractmethod
    def validate_configuration(self) -> bool:
        """Validate all configuration parameters."""
        pass


class ComponentMissingError(Exception):
    """Raised when a required component is missing."""
    pass


class ComponentValidationError(Exception):
    """Raised when component validation fails.""" 
    pass


class ConfigurationError(Exception):
    """Raised when configuration is invalid."""
    pass


# Interface Version for compatibility checking
INTERFACE_VERSION = "1.0.0"


def validate_interface_compatibility(component_version: str) -> bool:
    """
    Validate that a component version is compatible with current interfaces.
    
    Args:
        component_version: Version string of the component
        
    Returns:
        True if compatible, False otherwise
    """
    # Simple version validation - can be enhanced with semantic versioning
    return component_version.startswith("1.0")
