"""
Idempotency Layer - Exactly-Once Processing
============================================

Provides exactly-once semantics for event and fill processing.

ID Generation Ownership (from plan Section 7.3):
| ID Type | Generated By | Formula |
|---------|--------------|---------|
| event_id | DeterministicEventDispatcher | SHA256(session_id + ...) |
| signal_id | StreamingSignalManager | f"{strategy_id}:{symbol}:{ts}:{seq}" |
| authorization_id | CentralRiskManager | f"auth:{signal_id}:{gate}" |
| order_id | OrderManagementSystem | f"{session_id}:{seq:08d}" |
| fill_id | PaperBrokerAdapter | f"{order_id}:{fill_seq:03d}" |

Components:
- IdGenerator: Thread-safe deterministic ID generation
- IdempotencyTracker: Processed ID tracking with LRU eviction

Author: StatArb_Gemini Core Engine
Version: 1.0.0 (Paper Trading Evolution - Phase 5)
"""

import hashlib
import logging
import threading
from collections import deque
from datetime import datetime
from typing import Any, Deque, Dict, Set, Tuple

logger = logging.getLogger(__name__)

class IdGenerator:
    """
    Thread-safe deterministic ID generation.

    One instance per component. Sequence counter is restored on recovery.

    Usage:
        gen = IdGenerator("dispatcher", "paper-20250115-0001")
        event_id = gen.generate_event_id("bar", "2025-01-15T10:30:00", "AAPL")
    """

    def __init__(self, component_name: str, session_id: str):
        """
        Initialize ID generator.

        Args:
            component_name: Name of component (for logging/debug)
            session_id: Session identifier
        """
        self.component = component_name
        self.session_id = session_id
        self._seq = 0
        self._lock = threading.Lock()

    def next_seq(self) -> int:
        """Get next sequence number (thread-safe)."""
        with self._lock:
            self._seq += 1
            return self._seq

    @property
    def current_seq(self) -> int:
        """Get current sequence number (for checkpointing)."""
        return self._seq

    def restore_seq(self, seq: int) -> None:
        """Restore sequence counter from checkpoint."""
        with self._lock:
            self._seq = seq
            logger.debug(f"{self.component} sequence restored to {seq}")

    def generate_event_id(
        self,
        event_type: str,
        market_ts_ns: int,
        symbol: str,
    ) -> str:
        """
        Generate deterministic event ID.

        Formula: SHA256(session_id + event_type + market_ts_ns + symbol + seq)[:16]
        """
        seq = self.next_seq()

        data = f"{self.session_id}:{event_type}:{market_ts_ns}:{symbol}:{seq}"
        hash_bytes = hashlib.sha256(data.encode()).hexdigest()[:16]

        return hash_bytes

    def generate_signal_id(
        self,
        strategy_id: str,
        symbol: str,
        market_ts: datetime,
    ) -> str:
        """
        Generate deterministic signal ID.

        Formula: f"{strategy_id}:{symbol}:{market_ts_iso}:{seq}"
        """
        seq = self.next_seq()
        ts_str = market_ts.strftime('%Y-%m-%dT%H:%M:%S')

        return f"{strategy_id}:{symbol}:{ts_str}:{seq:04d}"

    def generate_authorization_id(
        self,
        signal_id: str,
        gate_passed: str,
    ) -> str:
        """
        Generate authorization ID.

        Formula: f"auth:{signal_id}:{gate_passed}"
        """
        return f"auth:{signal_id}:{gate_passed}"

    def generate_order_id(self) -> str:
        """
        Generate order ID.

        Formula: f"{session_id}:{seq:08d}"
        """
        seq = self.next_seq()
        return f"{self.session_id}:{seq:08d}"

    def generate_fill_id(self, order_id: str, fill_seq: int) -> str:
        """
        Generate fill ID.

        Formula: f"{order_id}:{fill_seq:03d}"
        """
        return f"{order_id}:{fill_seq:03d}"

class IdempotencyTracker:
    """
    Tracks processed IDs to prevent duplicate processing.

    Uses LRU eviction to bound memory usage.

    Usage:
        tracker = IdempotencyTracker(max_history=100_000)

        if tracker.is_processed('event', event_id):
            return  # Skip duplicate

        # Process event
        process(event)
        tracker.mark_processed('event', event_id)
    """

    def __init__(self, max_history: int = 100_000):
        """
        Initialize idempotency tracker.

        Args:
            max_history: Maximum IDs to track (LRU eviction beyond this)
        """
        self.max_history = max_history

        # Separate sets for different ID types
        self.processed_event_ids: Set[str] = set()
        self.processed_signal_ids: Set[str] = set()
        self.processed_fill_ids: Set[str] = set()

        # LRU queue: (id_type, id_value)
        self._lru: Deque[Tuple[str, str]] = deque()

        # Thread safety
        self._lock = threading.Lock()

        # Stats
        self._stats = {
            'checks': 0,
            'duplicates_found': 0,
            'ids_tracked': 0,
            'evictions': 0,
        }

    def _get_set_for_type(self, id_type: str) -> Set[str]:
        """Get the set for a given ID type."""
        if id_type == 'event':
            return self.processed_event_ids
        elif id_type == 'signal':
            return self.processed_signal_ids
        elif id_type == 'fill':
            return self.processed_fill_ids
        else:
            # Generic fallback
            return self.processed_event_ids

    def is_processed(self, id_type: str, id_value: str) -> bool:
        """
        Check if ID was already processed.

        Args:
            id_type: Type of ID ('event', 'signal', 'fill')
            id_value: The ID value

        Returns:
            True if already processed
        """
        with self._lock:
            self._stats['checks'] += 1
            target = self._get_set_for_type(id_type)

            if id_value in target:
                self._stats['duplicates_found'] += 1
                return True
            return False

    def mark_processed(self, id_type: str, id_value: str) -> None:
        """
        Mark ID as processed.

        Args:
            id_type: Type of ID ('event', 'signal', 'fill')
            id_value: The ID value
        """
        with self._lock:
            target = self._get_set_for_type(id_type)
            target.add(id_value)
            self._lru.append((id_type, id_value))
            self._stats['ids_tracked'] += 1

            # Evict oldest if at capacity
            while len(self._lru) > self.max_history:
                oldest_type, oldest_value = self._lru.popleft()
                oldest_set = self._get_set_for_type(oldest_type)
                oldest_set.discard(oldest_value)
                self._stats['evictions'] += 1

    def check_and_mark(self, id_type: str, id_value: str) -> bool:
        """
        Atomically check if processed and mark if not.

        Args:
            id_type: Type of ID
            id_value: The ID value

        Returns:
            True if was already processed (duplicate)
            False if new (and now marked as processed)
        """
        with self._lock:
            self._stats['checks'] += 1
            target = self._get_set_for_type(id_type)

            if id_value in target:
                self._stats['duplicates_found'] += 1
                return True

            # Mark as processed
            target.add(id_value)
            self._lru.append((id_type, id_value))
            self._stats['ids_tracked'] += 1

            # Evict if needed
            while len(self._lru) > self.max_history:
                oldest_type, oldest_value = self._lru.popleft()
                self._get_set_for_type(oldest_type).discard(oldest_value)
                self._stats['evictions'] += 1

            return False

    def clear(self) -> None:
        """Clear all tracked IDs."""
        with self._lock:
            self.processed_event_ids.clear()
            self.processed_signal_ids.clear()
            self.processed_fill_ids.clear()
            self._lru.clear()

    def get_stats(self) -> Dict[str, int]:
        """Get tracker statistics."""
        with self._lock:
            return {
                **self._stats,
                'event_ids_count': len(self.processed_event_ids),
                'signal_ids_count': len(self.processed_signal_ids),
                'fill_ids_count': len(self.processed_fill_ids),
            }

    def get_state_for_checkpoint(self) -> Dict[str, Any]:
        """Get state for checkpointing."""
        with self._lock:
            # Only save recent IDs (last N for each type) using LRU order
            recent_limit = 10_000

            # Get most recent IDs from LRU queue for each type
            recent_events = []
            recent_signals = []
            recent_fills = []

            # Iterate LRU in reverse (most recent first)
            for id_type, id_value in reversed(self._lru):
                if id_type == 'event' and len(recent_events) < recent_limit:
                    if id_value not in recent_events:  # Avoid duplicates
                        recent_events.append(id_value)
                elif id_type == 'signal' and len(recent_signals) < recent_limit:
                    if id_value not in recent_signals:
                        recent_signals.append(id_value)
                elif id_type == 'fill' and len(recent_fills) < 1000:
                    if id_value not in recent_fills:
                        recent_fills.append(id_value)

            return {
                'recent_event_ids': recent_events,
                'recent_signal_ids': recent_signals,
                'recent_fill_ids': recent_fills,
            }

    def restore_from_checkpoint(self, state: Dict[str, Any]) -> None:
        """Restore state from checkpoint."""
        with self._lock:
            # Clear sets directly (not via self.clear() to avoid deadlock)
            self.processed_event_ids.clear()
            self.processed_signal_ids.clear()
            self.processed_fill_ids.clear()
            self._lru.clear()

            for eid in state.get('recent_event_ids', []):
                self.processed_event_ids.add(eid)
                self._lru.append(('event', eid))

            for sid in state.get('recent_signal_ids', []):
                self.processed_signal_ids.add(sid)
                self._lru.append(('signal', sid))

            for fid in state.get('recent_fill_ids', []):
                self.processed_fill_ids.add(fid)
                self._lru.append(('fill', fid))

            logger.info(
                f"Restored idempotency state: "
                f"{len(self.processed_event_ids)} events, "
                f"{len(self.processed_signal_ids)} signals, "
                f"{len(self.processed_fill_ids)} fills"
            )

def generate_session_id(prefix: str = "paper") -> str:
    """
    Generate a session ID.

    Format: "{prefix}-{date}-{seq:04d}"
    Example: "paper-20250115-0001"

    Note: Caller should track run_seq and persist it.
    """
    from datetime import date
    today = date.today().strftime('%Y%m%d')
    # Simple random suffix for uniqueness
    import random
    seq = random.randint(1, 9999)
    return f"{prefix}-{today}-{seq:04d}"

