papertest:
  data:
    symbols: ["AAPL", "MSFT"]
    start_date: "2024-12-18"
    end_date: "2024-12-20"
    interval: "1min"
    replay_speed: "FAST_10X"
    simulate_market_hours: true

  buffers:
    size: 800
    warmup_required: 300


